// Source (UEFA 5-year Club Ranking 2026, top 50):
// https://kassiesa.net/uefa/data/method5/trank2026.html
export const TOP_50_EURO_CLUBS = [
  'Real Madrid',
  'Bayern München',
  'Liverpool',
  'Internazionale',
  'Manchester City',
  'Paris Saint-Germain',
  'FC Barcelona',
  'Arsenal',
  'Bayer Leverkusen',
  'Borussia Dortmund',
  'Atlético Madrid',
  'Chelsea',
  'AS Roma',
  'Benfica',
  'Atalanta',
  'Sporting CP Lisbon',
  'Eintracht Frankfurt',
  'Tottenham Hotspur',
  'FC Porto',
  'Manchester United',
  'Club Brugge',
  'Fiorentina',
  'Real Betis',
  'Aston Villa',
  'Juventus',
  'PSV Eindhoven',
  'Feyenoord',
  'West Ham United',
  'Lille OSC',
  'AC Milan',
  'Olympique Lyon',
  'Bodø/Glimt',
  'Napoli',
  'Olympiakos Piraeus',
  'AZ Alkmaar',
  'RB Leipzig',
  'Glasgow Rangers',
  'Villarreal',
  'Lazio',
  'Ajax',
  'Sporting Braga',
  'Fenerbahçe',
  'Real Sociedad',
  'AS Monaco',
  'FC København',
  'Olympique Marseille',
  'Galatasaray',
  'Shakhtar Donetsk',
  'Ferencváros',
  'Viktoria Plzen',
] as const

