import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

export const CLUB_LINEUPS_PART5: Record<string, ClubLineupData> = {
  'Tottenham Hotspur': {
    start: [
      L('GK', 'Уго Льорис', 'Hugo Lloris'),
      L('LB', 'Кайл Уокер', 'Kyle Walker'),
      L('CB', 'Тоби Алдервейрелд', 'Toby Alderweireld'),
      L('CB', 'Ян Вертонген', 'Jan Vertonghen'),
      L('RB', 'Киран Триппьер', 'Kieran Trippier'),
      L('LM', 'Сон Хын Мин', 'Son Heung-min'),
      L('CM', 'Кристиан Эриксен', 'Christian Eriksen'),
      L('CM', 'Мусса Дембеле', 'Mousa Dembélé'),
      L('RM', 'Гарет Бэйл', 'Gareth Bale'),
      L('ST', 'Харри Кейн', 'Harry Kane'),
      L('ST', 'Димитар Бербатов', 'Dimitar Berbatov'),
    ],
    bench: [
      L('GK', 'Пол Робинсон', 'Paul Robinson'),
      L('DF', 'Ледли Кинг', 'Ledley King'),
      L('DF', 'Мики ван де Вен', 'Micky van de Ven'),
      L('MF', 'Деле Алли', 'Dele Alli'),
      L('MF', 'Лука Модрич', 'Luka Modrić'),
      L('FW', 'Робби Кин', 'Robbie Keane'),
      L('FW', 'Петер Крауч', 'Peter Crouch'),
    ],
  },
  Valencia: {
    start: [
      L('GK', 'Сантьяго Канисарес', 'Santiago Cañizares'),
      L('LB', 'Жорди Альба', 'Jordi Alba'),
      L('CB', 'Давид Альбельда', 'David Albelda'),
      L('CB', 'Карлос Марчена', 'Carlos Marchena'),
      L('RB', 'Мигель', 'Miguel'),
      L('LM', 'Висенте', 'Vicente'),
      L('CM', 'Рубен Бараха', 'Rubén Baraja'),
      L('CM', 'Пабло Аймар', 'Pablo Aimar'),
      L('RM', 'Хакин', 'Joaquín'),
      L('ST', 'Давид Вилья', 'David Villa'),
      L('ST', 'Хуан Мата', 'Juan Mata'),
    ],
    bench: [
      L('GK', 'Диего Алвес', 'Diego Alves'),
      L('DF', 'Роберто Айяла', 'Roberto Ayala'),
      L('DF', 'Айтор Паредес', 'Aitor Paredes'),
      L('MF', 'Франсиско Кампос', 'Francisco Campos'),
      L('MF', 'Эвер Банега', 'Éver Banega'),
      L('FW', 'Пабло Паредес', 'Pablo Paredes'),
      L('FW', 'Рубен Паредес', 'Rubén Paredes'),
    ],
  },
  'Werder Bremen': {
    start: [
      L('GK', 'Тим Визе', 'Tim Wiese'),
      L('LB', 'Микаэль Нильссон', 'Mikael Nilsson'),
      L('CB', 'Пер Мертезакер', 'Per Mertesacker'),
      L('CB', 'Налдо', 'Naldo'),
      L('RB', 'Клеменс Фриц', 'Clemens Fritz'),
      L('LM', 'Месут Озиль', 'Mesut Özil'),
      L('CM', 'Диего', 'Diego'),
      L('CM', 'Торстен Фрингс', 'Torsten Frings'),
      L('RM', 'Аарон Хант', 'Aaron Hunt'),
      L('ST', 'Клаудио Писарро', 'Claudio Pizarro'),
      L('ST', 'Мирослав Клозе', 'Miroslav Klose'),
    ],
    bench: [
      L('GK', 'Андреас Райнке', 'Andreas Reinke'),
      L('DF', 'Петри Пасанен', 'Petri Pasanen'),
      L('DF', 'Себастьян Прёль', 'Sebastian Prödl'),
      L('MF', 'Франк Бауман', 'Frank Baumann'),
      L('MF', 'Тимо Боровски', 'Timo Borowski'),
      L('FW', 'Маркус Русенберг', 'Markus Rosenberg'),
      L('FW', 'Боян Кркич', 'Bojan Krkić'),
    ],
  },
  'Zenit Saint Petersburg': {
    start: [
      L('GK', 'Вячеслав Малафеев', 'Vyacheslav Malafeev'),
      L('LB', 'Юрий Жирков', 'Yuri Zhirkov'),
      L('CB', 'Николас Ломбертс', 'Nicolas Lombaerts'),
      L('CB', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('RB', 'Александр Анюков', 'Aleksandr Anyukov'),
      L('LM', 'Данни', 'Danny'),
      L('CM', 'Игорь Денисов', 'Igor Denisov'),
      L('CM', 'Аксель Витсель', 'Axel Witsel'),
      L('RM', 'Виктор Файзулин', 'Viktor Faizulin'),
      L('ST', 'Артём Дзюба', 'Artem Dzyuba'),
      L('ST', 'Халк', 'Hulk'),
    ],
    bench: [
      L('GK', 'Юрий Лодыгин', 'Yuri Lodygin'),
      L('DF', 'Луиш Нету', 'Luís Neto'),
      L('DF', 'Илья Кутепов', 'Ilya Kutepov'),
      L('MF', 'Матиас Краневиттер', 'Matías Kranevitter'),
      L('MF', 'Роберт Мак', 'Robert Mak'),
      L('FW', 'Александр Кержаков', 'Aleksandr Kerzhakov'),
      L('FW', 'Саломон Рондон', 'Salomón Rondón'),
    ],
  },
}
