import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

export const CLUB_LINEUPS_PART3: Record<string, ClubLineupData> = {
  Lyon: {
    start: [
      L('GK', 'Грегори Купе', 'Grégory Coupet'),
      L('LB', 'Антони Ревейер', 'Anthony Réveillère'),
      L('CB', 'Крис', 'Cris'),
      L('CB', 'Клаудио Касапа', 'Claudio Caçapa'),
      L('RB', 'Франсуа Клерк', 'François Clerc'),
      L('LM', 'Флоран Малуда', 'Florent Malouda'),
      L('CM', 'Жуниньо Пернамбукано', 'Juninho Pernambucano'),
      L('CM', 'Михаэль Эссьен', 'Michael Essien'),
      L('RM', 'Сидней Гову', 'Sidney Govou'),
      L('ST', 'Карим Бензема', 'Karim Benzema'),
      L('ST', 'Сонни Андерсон', 'Sonny Anderson'),
    ],
    bench: [
      L('GK', 'Уго Льорис', 'Hugo Lloris'),
      L('DF', 'Кристиан Валь', 'Christian Valle'),
      L('DF', 'Матье Бодмер', 'Mathieu Bodmer'),
      L('MF', 'Ким Чельстрем', 'Kim Källström'),
      L('MF', 'Эдерсон', 'Ederson'),
      L('FW', 'Бафетимби Гомис', 'Bafétimbi Gomis'),
      L('FW', 'Лисандро Лопес', 'Lisandro López'),
    ],
  },
  'Manchester City': {
    start: [
      L('GK', 'Эдерсон', 'Ederson'),
      L('LB', 'Гаэль Клиши', 'Gaël Clichy'),
      L('CB', 'Венсан Компани', 'Vincent Kompany'),
      L('CB', 'Рубен Диаш', 'Rúben Dias'),
      L('RB', 'Пабло Сабалета', 'Pablo Zabaleta'),
      L('LM', 'Давид Сильва', 'David Silva'),
      L('CM', 'Кевин Де Брюйне', 'Kevin De Bruyne'),
      L('CM', 'Яя Туре', 'Yaya Touré'),
      L('RM', 'Бернарду Силва', 'Bernardo Silva'),
      L('ST', 'Серхио Агуэро', 'Sergio Agüero'),
      L('ST', 'Эрлинг Холанн', 'Erling Haaland'),
    ],
    bench: [
      L('GK', 'Джо Харт', 'Joe Hart'),
      L('DF', 'Кайл Уокер', 'Kyle Walker'),
      L('DF', 'Жуан Канселу', 'João Cancelo'),
      L('MF', 'Фил Фоден', 'Phil Foden'),
      L('MF', 'Родри', 'Rodri'),
      L('FW', 'Рахим Стерлинг', 'Raheem Sterling'),
      L('FW', 'Карлос Тевес', 'Carlos Tévez'),
    ],
  },
  'Manchester United': {
    start: [
      L('GK', 'Петер Шмейхель', 'Peter Schmeichel'),
      L('LB', 'Патрис Эвра', 'Patrice Evra'),
      L('CB', 'Рио Фердинанд', 'Rio Ferdinand'),
      L('CB', 'Неманья Видич', 'Nemanja Vidić'),
      L('RB', 'Гари Невилл', 'Gary Neville'),
      L('LM', 'Райан Гиггз', 'Ryan Giggs'),
      L('CM', 'Рой Кин', 'Roy Keane'),
      L('CM', 'Пол Скоулз', 'Paul Scholes'),
      L('RM', 'Дэвид Бекхэм', 'David Beckham'),
      L('ST', 'Криштиану Роналду', 'Cristiano Ronaldo'),
      L('ST', 'Уэйн Руни', 'Wayne Rooney'),
    ],
    bench: [
      L('GK', 'Эдвин ван дер Сар', 'Edwin van der Sar'),
      L('DF', 'Яп Стам', 'Jaap Stam'),
      L('DF', 'Микаэль Сильвестр', 'Mikaël Silvestre'),
      L('MF', 'Майкл Каррик', 'Michael Carrick'),
      L('MF', 'Оуэн Харгривз', 'Owen Hargreaves'),
      L('FW', 'Руд ван Нистелрой', 'Ruud van Nistelrooy'),
      L('FW', 'Энди Коул', 'Andy Cole'),
    ],
  },
  Marseille: {
    start: [
      L('GK', 'Стив Манданда', 'Steve Mandanda'),
      L('LB', 'Тае Таиво', 'Taye Taiwo'),
      L('CB', 'Василис Боли', 'Basile Boli'),
      L('CB', 'Лоран Блан', 'Laurent Blanc'),
      L('RB', 'Бонна Сарр', 'Bouna Sarr'),
      L('LM', 'Димитри Пайет', 'Dimitri Payet'),
      L('CM', 'Матье Вальбуэна', 'Mathieu Valbuena'),
      L('CM', 'Дидье Дешам', 'Didier Deschamps'),
      L('RM', 'Франк Рибери', 'Franck Ribéry'),
      L('ST', 'Дидье Дрогба', 'Didier Drogba'),
      L('ST', 'Андре-Пьер Жиньяк', 'André-Pierre Gignac'),
    ],
    bench: [
      L('GK', 'Йоанн Пеле', 'Yohann Pelé'),
      L('DF', 'Род Фанни', 'Rod Fanni'),
      L('DF', 'Жорди Амави', 'Jordi Amavi'),
      L('MF', 'Абду Диавара', 'Abdou Diarra'),
      L('MF', 'Жан-Филипп Гбамен', 'Jean-Philippe Gbamin'),
      L('FW', 'Валер Жермен', 'Valère Germain'),
      L('FW', 'Флориан Товен', 'Florian Thauvin'),
    ],
  },
  'AC Milan': {
    start: [
      L('GK', 'Дида', 'Dida'),
      L('LB', 'Паоло Мальдини', 'Paolo Maldini'),
      L('CB', 'Алессандро Неста', 'Alessandro Nesta'),
      L('CB', 'Яп Стам', 'Jaap Stam'),
      L('RB', 'Кафу', 'Cafu'),
      L('LM', 'Кларенс Зеедорф', 'Clarence Seedorf'),
      L('CM', 'Андреа Пирло', 'Andrea Pirlo'),
      L('CM', 'Дженнаро Гаттузо', 'Gennaro Gattuso'),
      L('RM', 'Кака', 'Kaká'),
      L('ST', 'Андрей Шевченко', 'Andriy Shevchenko'),
      L('ST', 'Филиппо Индзаги', 'Filippo Inzaghi'),
    ],
    bench: [
      L('GK', 'Кристиан Аббьяти', 'Christian Abbiati'),
      L('DF', 'Алессандро Костакурта', 'Alessandro Costacurta'),
      L('DF', 'Массимо Оддо', 'Massimo Oddo'),
      L('MF', 'Жервиньо', 'Gervinho'),
      L('MF', 'Кевин-Принс Боатенг', 'Kevin-Prince Boateng'),
      L('FW', 'Джордж Веа', 'George Weah'),
      L('FW', 'Марко ван Бастен', 'Marco van Basten'),
    ],
  },
  'AS Monaco': {
    start: [
      L('GK', 'Фабьен Бартез', 'Fabien Barthez'),
      L('LB', 'Патрис Эвра', 'Patrice Evra'),
      L('CB', 'Рафаэль Маркес', 'Rafael Márquez'),
      L('CB', 'Себастьен Скиллачи', 'Sébastien Squillaci'),
      L('RB', 'Майкон', 'Maicon'),
      L('LM', 'Жером Ротен', 'Jérôme Rothen'),
      L('CM', 'Лудовик Жюли', 'Ludovic Giuly'),
      L('CM', 'Клод Макелеле', 'Claude Makélélé'),
      L('RM', 'Жуан Моутинью', 'João Moutinho'),
      L('ST', 'Радамель Фалькао', 'Radamel Falcao'),
      L('ST', 'Килиан Мбаппе', 'Kylian Mbappé'),
    ],
    bench: [
      L('GK', 'Даниэль Субашич', 'Danijel Subašić'),
      L('DF', 'Эрик Абидаль', 'Éric Abidal'),
      L('DF', 'Жюльен Родригес', 'Julien Rodriguez'),
      L('MF', 'Яник Феррейра Карраско', 'Yannick Ferreira Carrasco'),
      L('MF', 'Томас Лемар', 'Thomas Lemar'),
      L('FW', 'Джамель Абдун', 'Djamel Abdoun'),
      L('FW', 'Хуан Пабло', 'Juan Pablo'),
    ],
  },
  Napoli: {
    start: [
      L('GK', 'Давид Оспина', 'David Ospina'),
      L('LB', 'Фаузи Гулам', 'Faouzi Ghoulam'),
      L('CB', 'Калиду Кулибали', 'Kalidou Koulibaly'),
      L('CB', 'Паоло Каннаваро', 'Paolo Cannavaro'),
      L('RB', 'Кристиан Маджо', 'Christian Maggio'),
      L('LM', 'Лоренцо Инсинье', 'Lorenzo Insigne'),
      L('CM', 'Марек Гамшик', 'Marek Hamšík'),
      L('CM', 'Жоржиньо', 'Jorginho'),
      L('RM', 'Хосе Кальехон', 'José Callejón'),
      L('ST', 'Эдинсон Кавани', 'Edinson Cavani'),
      L('ST', 'Гонсало Игуаин', 'Gonzalo Higuaín'),
    ],
    bench: [
      L('GK', 'Алекс Мерет', 'Alex Meret'),
      L('DF', 'Джованни Ди Лоренцо', 'Giovanni Di Lorenzo'),
      L('DF', 'Никлас Зюле', 'Niklas Süle'),
      L('MF', 'Пётр Зелиньски', 'Piotr Zieliński'),
      L('MF', 'Аллан', 'Allan'),
      L('FW', 'Дрис Мертенс', 'Dries Mertens'),
      L('FW', 'Аркадиуш Милик', 'Arkadiusz Milik'),
    ],
  },
  'Paris Saint-Germain': {
    start: [
      L('GK', 'Джанлуиджи Буффон', 'Gianluigi Buffon'),
      L('LB', 'Максвелл', 'Maxwell'),
      L('CB', 'Тиаго Силва', 'Thiago Silva'),
      L('CB', 'Маркиньос', 'Marquinhos'),
      L('RB', 'Дани Алвес', 'Dani Alves'),
      L('LM', 'Роналдиньо', 'Ronaldinho'),
      L('CM', 'Марко Верратти', 'Marco Verratti'),
      L('CM', 'Адриен Рабьо', 'Adrien Rabiot'),
      L('RM', 'Анхель Ди Мария', 'Ángel Di María'),
      L('ST', 'Златан Ибрагимович', 'Zlatan Ibrahimović'),
      L('ST', 'Эдинсон Кавани', 'Edinson Cavani'),
    ],
    bench: [
      L('GK', 'Кейлор Навас', 'Keylor Navas'),
      L('DF', 'Преснель Кимпембе', 'Presnel Kimpembe'),
      L('DF', 'Жан-Кристоф Баэбек', 'Jean-Christophe Bahebeck'),
      L('MF', 'Блез Матюиди', 'Blaise Matuidi'),
      L('MF', 'Хатем Бен Арфа', 'Hatem Ben Arfa'),
      L('FW', 'Неймар', 'Neymar'),
      L('FW', 'Килиан Мбаппе', 'Kylian Mbappé'),
    ],
  },
}
