import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

export const CLUB_LINEUPS_PART4: Record<string, ClubLineupData> = {
  'PSV Eindhoven': {
    start: [
      L('GK', 'Хейрел Гомеш', 'Heurelho Gomes'),
      L('LB', 'Эрик Питерс', 'Erik Pieters'),
      L('CB', 'Алекс', 'Alex'),
      L('CB', 'Вилфрид Бума', 'Wilfred Bouma'),
      L('RB', 'Андре Ойер', 'André Ooijer'),
      L('LM', 'Пак Чи Сон', 'Park Ji-sung'),
      L('CM', 'Марк ван Боммел', 'Mark van Bommel'),
      L('CM', 'Филлип Коку', 'Phillip Cocu'),
      L('RM', 'Арьен Роббен', 'Arjen Robben'),
      L('ST', 'Руд ван Нистелрой', 'Ruud van Nistelrooy'),
      L('ST', 'Матея Кежман', 'Mateja Kežman'),
    ],
    bench: [
      L('GK', 'Рональд Ватеррёйс', 'Ronald Waterreus'),
      L('DF', 'Ян Кромкамп', 'Jan Kromkamp'),
      L('DF', 'Кевин Хор', 'Kevin Hofland'),
      L('MF', 'Ибрахим Афеллай', 'Ibrahim Afellay'),
      L('MF', 'Ван дер Меер', 'Van der Meer'),
      L('FW', 'Юрген Лок', 'Jürgen Lok'),
      L('FW', 'Деннис Роммедаль', 'Dennis Rommedahl'),
    ],
  },
  'FC Porto': {
    start: [
      L('GK', 'Витор Баия', 'Vítor Baía'),
      L('LB', 'Нуну Валенте', 'Nuno Valente'),
      L('CB', 'Рикарду Карвалью', 'Ricardo Carvalho'),
      L('CB', 'Жорже Кошта', 'Jorge Costa'),
      L('RB', 'Паулу Феррейра', 'Paulo Ferreira'),
      L('LM', 'Деку', 'Deco'),
      L('CM', 'Манише', 'Maniche'),
      L('CM', 'Коштинья', 'Costinha'),
      L('RM', 'Луиш Фигу', 'Luís Figo'),
      L('ST', 'Радамель Фалькао', 'Radamel Falcao'),
      L('ST', 'Халк', 'Hulk'),
    ],
    bench: [
      L('GK', 'Элтон', 'Helton'),
      L('DF', 'Пепе', 'Pepe'),
      L('DF', 'Али Сиссоко', 'Ali Sissoko'),
      L('MF', 'Жуан Моутинью', 'João Moutinho'),
      L('MF', 'Фредди Гуарин', 'Fredy Guarín'),
      L('FW', 'Джексон Мартинес', 'Jackson Martínez'),
      L('FW', 'Клаудио Писарро', 'Claudio Pizarro'),
    ],
  },
  'Real Madrid': {
    start: [
      L('GK', 'Икер Касильяс', 'Iker Casillas'),
      L('LB', 'Роберто Карлос', 'Roberto Carlos'),
      L('CB', 'Серхио Рамос', 'Sergio Ramos'),
      L('CB', 'Пепе', 'Pepe'),
      L('RB', 'Мичел Сальгадо', 'Michel Salgado'),
      L('LM', 'Зинедин Зидан', 'Zinedine Zidane'),
      L('CM', 'Клод Макелеле', 'Claude Makélélé'),
      L('CM', 'Лука Модрич', 'Luka Modrić'),
      L('RM', 'Дэвид Бекхэм', 'David Beckham'),
      L('ST', 'Криштиану Роналду', 'Cristiano Ronaldo'),
      L('ST', 'Рауль Гонсалес', 'Raúl González'),
    ],
    bench: [
      L('GK', 'Тибо Куртуа', 'Thibaut Courtois'),
      L('DF', 'Фернандо Йерро', 'Fernando Hierro'),
      L('DF', 'Карлос Марчена', 'Carlos Marchena'),
      L('MF', 'Каземиро', 'Casemiro'),
      L('MF', 'Федерико Вальверде', 'Federico Valverde'),
      L('FW', 'Карим Бензема', 'Karim Benzema'),
      L('FW', 'Гонсало Игуаин', 'Gonzalo Higuaín'),
    ],
  },
  'AS Roma': {
    start: [
      L('GK', 'Алиссон Бекер', 'Alisson Becker'),
      L('LB', 'Кафу', 'Cafu'),
      L('CB', 'Алдаир', 'Aldair'),
      L('CB', 'Вальтер Самуэль', 'Walter Samuel'),
      L('RB', 'Кристиан Пануччи', 'Christian Panucci'),
      L('LM', 'Даниэле Де Росси', 'Daniele De Rossi'),
      L('CM', 'Раджа Наингголан', 'Radja Nainggolan'),
      L('CM', 'Миралем Пьянич', 'Miralem Pjanić'),
      L('RM', 'Франческо Тотти', 'Francesco Totti'),
      L('ST', 'Эдин Джеко', 'Edin Džeko'),
      L('ST', 'Габриэль Батистута', 'Gabriel Batistuta'),
    ],
    bench: [
      L('GK', 'Дони', 'Doni'),
      L('DF', 'Костас Манолас', 'Kostas Manolas'),
      L('DF', 'Федерико Фасио', 'Federico Fazio'),
      L('MF', 'Кевин Строотман', 'Kevin Strootman'),
      L('MF', 'Алессандро Флоренци', 'Alessandro Florenzi'),
      L('FW', 'Винченцо Монтелла', 'Vincenzo Montella'),
      L('FW', 'Антонио Кассано', 'Antonio Cassano'),
    ],
  },
  'Rubin Kazan': {
    start: [
      L('GK', 'Сергей Рыжиков', 'Sergey Ryzhikov'),
      L('LB', 'Кристиан Ансальди', 'Cristian Ansaldi'),
      L('CB', 'Роман Шаронов', 'Roman Sharonov'),
      L('CB', 'Сесар Навас', 'César Navas'),
      L('RB', 'Олег Кузьмин', 'Oleg Kuzmin'),
      L('LM', 'Гёкдениз Карадениз', 'Gökdeniz Karadeniz'),
      L('CM', 'Алан Касаев', 'Alan Kasaev'),
      L('CM', 'Бибрас Натхо', 'Bibras Natkho'),
      L('RM', 'Карлос Эдуардо', 'Carlos Eduardo'),
      L('ST', 'Александр Бухаров', 'Aleksandr Bukharov'),
      L('ST', 'Нельсон Аэдо Вальдес', 'Nelson Haedo Valdez'),
    ],
    bench: [
      L('GK', 'Сослан Джанаев', 'Soslan Dzhanayev'),
      L('DF', 'Владимир Гранат', 'Vladimir Granat'),
      L('DF', 'Соломон Кверквелия', 'Solomon Kvirkvelia'),
      L('MF', 'Пётр Быстров', 'Pyotr Bystrov'),
      L('MF', 'Вячеслав Караваев', 'Vyacheslav Karavayev'),
      L('FW', 'Владимир Дядюн', 'Vladimir Dyadyun'),
      L('FW', 'Сердар Азмун', 'Sardar Azmoun'),
    ],
  },
  'Schalke 04': {
    start: [
      L('GK', 'Мануэль Нойер', 'Manuel Neuer'),
      L('LB', 'Кристиан Фукс', 'Christian Fuchs'),
      L('CB', 'Бенедикт Хёведес', 'Benedikt Höwedes'),
      L('CB', 'Йоэль Матип', 'Joel Matip'),
      L('RB', 'Рафинья', 'Rafinha'),
      L('LM', 'Месут Озиль', 'Mesut Özil'),
      L('CM', 'Иван Ракитич', 'Ivan Rakitić'),
      L('CM', 'Юлиан Дракслер', 'Julian Draxler'),
      L('RM', 'Лерой Сане', 'Leroy Sané'),
      L('ST', 'Клас-Ян Хюнтелар', 'Klaas-Jan Huntelaar'),
      L('ST', 'Рауль Гонсалес', 'Raúl González'),
    ],
    bench: [
      L('GK', 'Ральф Ферманн', 'Ralf Fährmann'),
      L('DF', 'Кристоф Метцельдер', 'Christoph Metzelder'),
      L('DF', 'Кевин Кураньи', 'Kevin Kurányi'),
      L('MF', 'Линкольн', 'Lincoln'),
      L('MF', 'Халил Алтынтоп', 'Halil Altıntop'),
      L('FW', 'Эббе Санд', 'Ebbe Sand'),
      L('FW', 'Джеральд Асамоа', 'Gerald Asamoah'),
    ],
  },
  Sevilla: {
    start: [
      L('GK', 'Андрес Палоп', 'Andrés Palop'),
      L('LB', 'Адриано Коррея', 'Adriano Correia'),
      L('CB', 'Диего Карлос', 'Diego Carlos'),
      L('CB', 'Хави Наварро', 'Javi Navarro'),
      L('RB', 'Дани Алвес', 'Dani Alves'),
      L('LM', 'Хесус Навас', 'Jesús Navas'),
      L('CM', 'Иван Ракитич', 'Ivan Rakitić'),
      L('CM', 'Эвер Банега', 'Ever Banega'),
      L('RM', 'Хосе Антонио Рейес', 'José Antonio Reyes'),
      L('ST', 'Луис Фабиано', 'Luís Fabiano'),
      L('ST', 'Фредерик Кануте', 'Frédéric Kanouté'),
    ],
    bench: [
      L('GK', 'Марко Дмитрович', 'Marko Dmitrović'),
      L('DF', 'Федерико Фасио', 'Federico Fazio'),
      L('DF', 'Мартин Касерес', 'Martín Cáceres'),
      L('MF', 'Вильям Карвалью', 'William Carvalho'),
      L('MF', 'Стивен Н’Зонзи', 'Steven N’Zonzi'),
      L('FW', 'Кевин Гамейро', 'Kevin Gameiro'),
      L('FW', 'Карлос Бака', 'Carlos Bacca'),
    ],
  },
  'Spartak Moscow': {
    start: [
      L('GK', 'Артём Ребров', 'Artem Rebrov'),
      L('LB', 'Дмитрий Комбаров', 'Dmitri Kombarov'),
      L('CB', 'Сергей Паршивлюк', 'Sergei Parshivlyuk'),
      L('CB', 'Николай Заболотный', 'Nikolai Zabolotny'),
      L('RB', 'Андрей Ещенко', 'Andrey Yeshchenko'),
      L('LM', 'Квинси Промес', 'Quincy Promes'),
      L('CM', 'Роман Зобнин', 'Roman Zobnin'),
      L('CM', 'Денис Глушаков', 'Denis Glushakov'),
      L('RM', 'Лоренсо Мельгарехо', 'Lorenzo Melgarejo'),
      L('ST', 'Александр Кокорин', 'Aleksandr Kokorin'),
      L('ST', 'Юра Мовсисян', 'Yura Movsisyan'),
    ],
    bench: [
      L('GK', 'Александр Максименко', 'Aleksandr Maksimenko'),
      L('DF', 'Илья Кутепов', 'Ilya Kutepov'),
      L('DF', 'Георгий Джикия', 'Georgi Dzhikiya'),
      L('MF', 'Артём Тимофеев', 'Artyom Timofeev'),
      L('MF', 'Александр Самедов', 'Aleksandr Samedov'),
      L('FW', 'Лукас Барриос', 'Lucas Barrios'),
      L('FW', 'Зе Луиш', 'Zé Luís'),
    ],
  },
}
