import { lineupLine as L } from './bestLineupHelpers'
import type { NationalLineupData } from './nationalBestLineups.types'

export const NATIONAL_LINEUPS_PART1: Record<string, NationalLineupData> = {
  Аргентина: {
    countryRu: 'Аргентина',
    start: [
      L('GK', 'Эмилиано Мартинес', 'Emiliano Martínez'),
      L('LB', 'Хавьер Санетти', 'Javier Zanetti'),
      L('CB', 'Роберто Айяла', 'Roberto Ayala'),
      L('CB', 'Вальтер Самуэль', 'Walter Samuel'),
      L('RB', 'Уго Ибарра', 'Hugo Ibarra'),
      L('LM', 'Анхель Ди Мария', 'Ángel Di María'),
      L('CM', 'Хавьер Маскерано', 'Javier Mascherano'),
      L('CM', 'Фернандо Гаго', 'Fernando Gago'),
      L('RM', 'Лионель Месси', 'Lionel Messi'),
      L('ST', 'Габриэль Батистута', 'Gabriel Batistuta'),
      L('ST', 'Серхио Агуэро', 'Sergio Agüero'),
    ],
    bench: [
      L('GK', 'Серхио Ромеро', 'Sergio Romero'),
      L('DF', 'Николас Отаменди', 'Nicolás Otamendi'),
      L('DF', 'Маркос Рохо', 'Marcos Rojo'),
      L('MF', 'Хуан Себастьян Верон', 'Juan Sebastián Verón'),
      L('MF', 'Пабло Аймар', 'Pablo Aimar'),
      L('FW', 'Гонсало Игуаин', 'Gonzalo Higuaín'),
      L('FW', 'Лаутаро Мартинес', 'Lautaro Martínez'),
    ],
  },
  Бразилия: {
    countryRu: 'Бразилия',
    start: [
      L('GK', 'Алиссон Бекер', 'Alisson Becker'),
      L('LB', 'Роберто Карлос', 'Roberto Carlos'),
      L('CB', 'Тиаго Силва', 'Thiago Silva'),
      L('CB', 'Лусио', 'Lucio'),
      L('RB', 'Кафу', 'Cafu'),
      L('LM', 'Роналдиньо', 'Ronaldinho'),
      L('CM', 'Кака', 'Kaká'),
      L('CM', 'Каземиро', 'Casemiro'),
      L('RM', 'Неймар', 'Neymar'),
      L('ST', 'Роналдо', 'Ronaldo'),
      L('ST', 'Ромарио', 'Romário'),
    ],
    bench: [
      L('GK', 'Жулио Сезар', 'Júlio César'),
      L('DF', 'Марсело', 'Marcelo'),
      L('DF', 'Дани Алвес', 'Dani Alves'),
      L('MF', 'Филиппе Коутиньо', 'Philippe Coutinho'),
      L('MF', 'Паулиньо', 'Paulinho'),
      L('FW', 'Ривалдо', 'Rivaldo'),
      L('FW', 'Адриано', 'Adriano'),
    ],
  },
  Франция: {
    countryRu: 'Франция',
    start: [
      L('GK', 'Уго Льорис', 'Hugo Lloris'),
      L('LB', 'Патрис Эвра', 'Patrice Evra'),
      L('CB', 'Лилиан Тюрам', 'Lilian Thuram'),
      L('CB', 'Рафаэль Варан', 'Raphaël Varane'),
      L('RB', 'Бакари Санья', 'Bacary Sagna'),
      L('LM', 'Тьерри Анри', 'Thierry Henry'),
      L('CM', 'Зинедин Зидан', 'Zinedine Zidane'),
      L('CM', 'Н’Голо Канте', 'N’Golo Kanté'),
      L('RM', 'Килиан Мбаппе', 'Kylian Mbappé'),
      L('ST', 'Карим Бензема', 'Karim Benzema'),
      L('ST', 'Давид Трезеге', 'David Trezeguet'),
    ],
    bench: [
      L('GK', 'Фабьен Бартез', 'Fabien Barthez'),
      L('DF', 'Лоран Блан', 'Laurent Blanc'),
      L('DF', 'Бенжамен Павар', 'Benjamin Pavard'),
      L('MF', 'Патрик Виейра', 'Patrick Vieira'),
      L('MF', 'Антуан Гризманн', 'Antoine Griezmann'),
      L('FW', 'Оливье Жиру', 'Olivier Giroud'),
      L('FW', 'Сильвен Вильтор', 'Sylvain Wiltord'),
    ],
  },
  Испания: {
    countryRu: 'Испания',
    start: [
      L('GK', 'Икер Касильяс', 'Iker Casillas'),
      L('LB', 'Жорди Альба', 'Jordi Alba'),
      L('CB', 'Карлес Пуйоль', 'Carles Puyol'),
      L('CB', 'Серхио Рамос', 'Sergio Ramos'),
      L('RB', 'Дани Карвахаль', 'Dani Carvajal'),
      L('LM', 'Андрес Иньеста', 'Andrés Iniesta'),
      L('CM', 'Хави', 'Xavi'),
      L('CM', 'Серхио Бускетс', 'Sergio Busquets'),
      L('RM', 'Давид Сильва', 'David Silva'),
      L('ST', 'Давид Вилья', 'David Villa'),
      L('ST', 'Фернандо Торрес', 'Fernando Torres'),
    ],
    bench: [
      L('GK', 'Давид де Хеа', 'David de Gea'),
      L('DF', 'Жерар Пике', 'Gerard Piqué'),
      L('DF', 'Альваро Арбелоа', 'Álvaro Arbeloa'),
      L('MF', 'Хаби Алонсо', 'Xabi Alonso'),
      L('MF', 'Сеск Фабрегас', 'Cesc Fàbregas'),
      L('FW', 'Альваро Мората', 'Álvaro Morata'),
      L('FW', 'Луис Энрике', 'Luis Enrique'),
    ],
  },
  Англия: {
    countryRu: 'Англия',
    start: [
      L('GK', 'Джордан Пакфорд', 'Jordan Pickford'),
      L('LB', 'Эшли Коул', 'Ashley Cole'),
      L('CB', 'Джон Терри', 'John Terry'),
      L('CB', 'Рио Фердинанд', 'Rio Ferdinand'),
      L('RB', 'Гари Невилл', 'Gary Neville'),
      L('LM', 'Стивен Джеррард', 'Steven Gerrard'),
      L('CM', 'Фрэнк Лэмпард', 'Frank Lampard'),
      L('CM', 'Пол Скоулз', 'Paul Scholes'),
      L('RM', 'Дэвид Бекхэм', 'David Beckham'),
      L('ST', 'Уэйн Руни', 'Wayne Rooney'),
      L('ST', 'Харри Кейн', 'Harry Kane'),
    ],
    bench: [
      L('GK', 'Дэвид Симен', 'David Seaman'),
      L('DF', 'Сол Кэмпбелл', 'Sol Campbell'),
      L('DF', 'Кайл Уокер', 'Kyle Walker'),
      L('MF', 'Джеймс Милнер', 'James Milner'),
      L('MF', 'Рахим Стерлинг', 'Raheem Sterling'),
      L('FW', 'Майкл Оуэн', 'Michael Owen'),
      L('FW', 'Джермейн Дефо', 'Jermain Defoe'),
    ],
  },
  Португалия: {
    countryRu: 'Португалия',
    start: [
      L('GK', 'Руй Патрисиу', 'Rui Patrício'),
      L('LB', 'Рафаэл Геррейру', 'Raphaël Guerreiro'),
      L('CB', 'Пепе', 'Pepe'),
      L('CB', 'Рубен Диаш', 'Rúben Dias'),
      L('RB', 'Жуан Канселу', 'João Cancelo'),
      L('LM', 'Бернарду Силва', 'Bernardo Silva'),
      L('CM', 'Жуан Моутинью', 'João Moutinho'),
      L('CM', 'Бруну Фернандеш', 'Bruno Fernandes'),
      L('RM', 'Луиш Фигу', 'Luís Figo'),
      L('ST', 'Криштиану Роналду', 'Cristiano Ronaldo'),
      L('ST', 'Диегу Жота', 'Diogo Jota'),
    ],
    bench: [
      L('GK', 'Витор Баия', 'Vítor Baía'),
      L('DF', 'Рикарду Карвалью', 'Ricardo Carvalho'),
      L('DF', 'Нуну Валенте', 'Nuno Valente'),
      L('MF', 'Деку', 'Deco'),
      L('MF', 'Рубен Невеш', 'Rúben Neves'),
      L('FW', 'Нуну Гомеш', 'Nuno Gomes'),
      L('FW', 'Жуан Феликс', 'João Félix'),
    ],
  },
}
