import { lineupLine as L } from './bestLineupHelpers'
import type { NationalLineupData } from './nationalBestLineups.types'

export const NATIONAL_LINEUPS_PART4: Record<string, NationalLineupData> = {
  Норвегия: {
    countryRu: 'Норвегия',
    start: [
      L('GK', 'Эрленд Йонсен', 'Erland Johnsen'),
      L('LB', 'Джон Арне Риисе', 'John Arne Riise'),
      L('CB', 'Бреде Хангеланн', 'Brede Hangeland'),
      L('CB', 'Хавард Нортвейт', 'Håvard Nordtveit'),
      L('RB', 'Омар Элабделлауи', 'Omar Elabdellaoui'),
      L('LM', 'Мартин Эдегор', 'Martin Ødegaard'),
      L('CM', 'Ховард Флор', 'Håvard Flo'),
      L('CM', 'Мортен Гамст Педерсен', 'Morten Gamst Pedersen'),
      L('RM', 'Петтер Сольберг', 'Petter Solberg'),
      L('ST', 'Эрлинг Холанн', 'Erling Haaland'),
      L('ST', 'Уле Гуннар Сульшер', 'Ole Gunnar Solskjær'),
    ],
    bench: [
      L('GK', 'Руне Эстли', 'Rune Østli'),
      L('DF', 'Торе Редер', 'Tore Røder'),
      L('DF', 'Кристиан Хаммер', 'Christian Hammer'),
      L('MF', 'Рубен Иверсен', 'Ruben Iversen'),
      L('MF', 'Томас Мюре', 'Thomas Møyre'),
      L('FW', 'Стеффен Иверсен', 'Steffen Iversen'),
      L('FW', 'Мохамед Эльюнусси', 'Mohamed Elyounoussi'),
    ],
  },
  Польша: {
    countryRu: 'Польша',
    start: [
      L('GK', 'Войцех Щенсны', 'Wojciech Szczęsny'),
      L('LB', 'Якуб Кивёр', 'Jakub Kiwior'),
      L('CB', 'Камиль Глик', 'Kamil Glik'),
      L('CB', 'Томаш Вальдох', 'Tomasz Waldoch'),
      L('RB', 'Лукаш Пищек', 'Łukasz Piszczek'),
      L('LM', 'Якуб Блащиковски', 'Jakub Błaszczykowski'),
      L('CM', 'Гжегож Крыховяк', 'Grzegorz Krychowiak'),
      L('CM', 'Пётр Зелиньски', 'Piotr Zieliński'),
      L('RM', 'Мацей Журавски', 'Maciej Żurawski'),
      L('ST', 'Роберт Левандовски', 'Robert Lewandowski'),
      L('ST', 'Эммануэль Олисадебе', 'Emmanuel Olisadebe'),
    ],
    bench: [
      L('GK', 'Лукаш Фабьянски', 'Łukasz Fabiański'),
      L('DF', 'Михал Жевлаков', 'Michał Żewłakow'),
      L('DF', 'Аркадиуш Реца', 'Arkadiusz Reca'),
      L('MF', 'Камиль Гросицки', 'Kamil Grosicki'),
      L('MF', 'Себастьян Миля', 'Sebastian Mila'),
      L('FW', 'Иренеуш Елень', 'Ireneusz Jeleń'),
      L('FW', 'Кшиштоф Пёнтек', 'Krzysztof Piątek'),
    ],
  },
  Сенегал: {
    countryRu: 'Сенегал',
    start: [
      L('GK', 'Эдуард Менди', 'Édouard Mendy'),
      L('LB', 'Садио Мане', 'Sadio Mané'),
      L('CB', 'Калиду Кулибали', 'Kalidou Koulibaly'),
      L('CB', 'Абдулайе Диалло', 'Abdoulaye Diallo'),
      L('RB', 'Юссуф Сабали', 'Youssouf Sabaly'),
      L('LM', 'Идрисса Гейе', 'Idrissa Gueye'),
      L('CM', 'Пап Буба Диоп', 'Papa Bouba Diop'),
      L('CM', 'Шейху Куяте', 'Cheikhou Kouyaté'),
      L('RM', 'Эль-Хаджи Диуф', 'El-Hadji Diouf'),
      L('ST', 'Анри Камара', 'Henri Camara'),
      L('ST', 'Исмаила Сарр', 'Ismaïla Sarr'),
    ],
    bench: [
      L('GK', 'Тони Сильва', 'Tony Sylva'),
      L('DF', 'Салиф Дьяо', 'Salif Diao'),
      L('DF', 'Ламин Сане', 'Lamine Sané'),
      L('MF', 'Мамаду Диарра', 'Mamadou Diarra'),
      L('MF', 'Алиу Сиссе', 'Aliou Cissé'),
      L('FW', 'Мамаду Ньянг', 'Mamadou Niang'),
      L('FW', 'М’Байе Ньянг', 'M’Baye Niang'),
    ],
  },
  Марокко: {
    countryRu: 'Марокко',
    start: [
      L('GK', 'Яссин Буну', 'Yassine Bounou'),
      L('LB', 'Нуссаир Мазрауи', 'Noussair Mazraoui'),
      L('CB', 'Мехди Бенатия', 'Mehdi Benatia'),
      L('CB', 'Ромен Саис', 'Romain Saïss'),
      L('RB', 'Ашраф Хакими', 'Achraf Hakimi'),
      L('LM', 'Хаким Зиеш', 'Hakim Ziyech'),
      L('CM', 'Софьян Амрабат', 'Sofyan Amrabat'),
      L('CM', 'Абдельхамид Сабири', 'Abdelhamid Sabiri'),
      L('RM', 'Юсеф Эн-Несири', 'Youssef En-Nesyri'),
      L('ST', 'Мустафа Хаджи', 'Mustapha Hadji'),
      L('ST', 'Абдерразак Хамдалла', 'Abderrazak Hamdallah'),
    ],
    bench: [
      L('GK', 'Мунир Мохамеди', 'Munir Mohammedi'),
      L('DF', 'Науфаль Эль-Араби', 'Noufhal El Arabi'),
      L('DF', 'Жавад Эль-Ямик', 'Jawad El Yamiq'),
      L('MF', 'Файсал Фаджр', 'Fayçal Fajr'),
      L('MF', 'Карим Эль-Ахмади', 'Karim El Ahmadi'),
      L('FW', 'Маруан Шамах', 'Marouane Chamakh'),
      L('FW', 'Азиз Бухаддуз', 'Aziz Bouhaddouz'),
    ],
  },
  Япония: {
    countryRu: 'Япония',
    start: [
      L('GK', 'Эйдзи Кавасима', 'Eiji Kawashima'),
      L('LB', 'Юто Нагатомо', 'Yuto Nagatomo'),
      L('CB', 'Мая Ёсида', 'Maya Yoshida'),
      L('CB', 'Цуёси Таки', 'Tsuyoshi Takai'),
      L('RB', 'Гэнки Харагути', 'Genki Haraguchi'),
      L('LM', 'Синдзи Кагава', 'Shinji Kagawa'),
      L('CM', 'Кэйсукэ Хонда', 'Keisuke Honda'),
      L('CM', 'Хидэтоси Наката', 'Hidetoshi Nakata'),
      L('RM', 'Сюнсукэ Накамура', 'Shunsuke Nakamura'),
      L('ST', 'Наохиро Такахара', 'Naohiro Takahara'),
      L('ST', 'Синдзи Окадзаки', 'Shinji Okazaki'),
    ],
    bench: [
      L('GK', 'Сюити Гонда', 'Shuichi Gonda'),
      L('DF', 'Масахико Иноха', 'Masahiko Inoha'),
      L('DF', 'Томоаки Макино', 'Tomoaki Makino'),
      L('MF', 'Дзюнъити Инамото', 'Junichi Inamoto'),
      L('MF', 'Такаси Инуи', 'Takashi Inui'),
      L('FW', 'Ёсито Окубо', 'Yoshito Okubo'),
      L('FW', 'Кэндзи Фукусима', 'Kenji Fukushima'),
    ],
  },
  'Южная Корея': {
    countryRu: 'Южная Корея',
    start: [
      L('GK', 'Ким Сын Гю', 'Kim Seung-gyu'),
      L('LB', 'Хон Чон Хо', 'Hong Jeong-ho'),
      L('CB', 'Ким Мин Джэ', 'Kim Min-jae'),
      L('CB', 'Хон Мён Бо', 'Hong Myung-bo'),
      L('RB', 'Ли Ён Пхё', 'Lee Young-pyo'),
      L('LM', 'Пак Чи Сон', 'Park Ji-sung'),
      L('CM', 'Ки Сон Ён', 'Ki Sung-yueng'),
      L('CM', 'Ли Чхон Су', 'Lee Chun-soo'),
      L('RM', 'Сон Хын Мин', 'Son Heung-min'),
      L('ST', 'Чха Ду Ри', 'Cha Du-ri'),
      L('ST', 'Ан Джон Хван', 'Ahn Jung-hwan'),
    ],
    bench: [
      L('GK', 'Чо Хён У', 'Jo Hyeon-woo'),
      L('DF', 'Ким Джин Су', 'Kim Jin-su'),
      L('DF', 'Квак Тхэ Хви', 'Kwak Tae-hwi'),
      L('MF', 'Ку Джа Чхоль', 'Koo Ja-cheol'),
      L('MF', 'Ли Дон Гук', 'Lee Dong-gook'),
      L('FW', 'Хван Ый Джо', 'Hwang Ui-jo'),
      L('FW', 'Пак Чу Ён', 'Park Chu-young'),
    ],
  },
}
