import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

/** Подсказки «Лучший состав» для режима РПЛ. */
export const RPL_CLUB_LINEUPS: Record<string, ClubLineupData> = {
  'Зенит (Санкт-Петербург)': {
    start: [
      L('GK', 'Вячеслав Малафеев', 'Vyacheslav Malafeev'),
      L('LB', 'Юрий Жирков', 'Yuri Zhirkov'),
      L('CB', 'Николас Ломбертс', 'Nicolas Lombaerts'),
      L('CB', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('RB', 'Александр Анюков', 'Aleksandr Anyukov'),
      L('LM', 'Данни', 'Danny'),
      L('CM', 'Игорь Денисов', 'Igor Denisov'),
      L('CM', 'Аксель Витсель', 'Axel Witsel'),
      L('RM', 'Виктор Файзулин', 'Viktor Faizulin'),
      L('ST', 'Артём Дзюба', 'Artem Dzyuba'),
      L('ST', 'Халк', 'Hulk'),
    ],
    bench: [
      L('GK', 'Михаил Кержаков', 'Mikhail Kerzhakov'),
      L('DF', 'Луиш Нету', 'Luís Neto'),
      L('DF', 'Доменико Кришито', 'Domenico Criscito'),
      L('MF', 'Константин Зырянов', 'Konstantin Zyryanov'),
      L('MF', 'Олег Шатов', 'Oleg Shatov'),
      L('FW', 'Александр Кержаков', 'Aleksandr Kerzhakov'),
      L('FW', 'Сердар Азмун', 'Sardar Azmoun'),
    ],
  },
  'ЦСКА (Москва)': {
    start: [
      L('GK', 'Игорь Акинфеев', 'Igor Akinfeev'),
      L('LB', 'Георгий Щенников', 'Georgi Shchennikov'),
      L('CB', 'Сергей Игнашевич', 'Sergei Ignashevich'),
      L('CB', 'Алексей Березуцкий', 'Aleksei Berezutski'),
      L('RB', 'Марио Фернандес', 'Mário Fernandes'),
      L('LM', 'Алан Дзагоев', 'Alan Dzagoev'),
      L('CM', 'Понтус Вернблум', 'Pontus Wernbloom'),
      L('CM', 'Никола Влашич', 'Nikola Vlašić'),
      L('RM', 'Милош Красич', 'Miloš Krasić'),
      L('ST', 'Вагнер Лав', 'Vágner Love'),
      L('ST', 'Сейду Думбия', 'Seydou Doumbia'),
    ],
    bench: [
      L('GK', 'Владимир Габулов', 'Vladimir Gabulov'),
      L('DF', 'Василий Березуцкий', 'Vasili Berezutski'),
      L('DF', 'Кирилл Набабкин', 'Kirill Nababkin'),
      L('MF', 'Евгений Алдонин', 'Yevgeny Aldonin'),
      L('MF', 'Кейсуке Хонда', 'Keisuke Honda'),
      L('FW', 'Ахмед Муса', 'Ahmed Musa'),
      L('FW', 'Томаш Нецид', 'Tomáš Necid'),
    ],
  },
  'Локомотив (Москва)': {
    start: [
      L('GK', 'Маринато Гильерме', 'Marinato Guilherme'),
      L('LB', 'Дмитрий Сенников', 'Dmitri Sennikov'),
      L('CB', 'Ведран Чорлука', 'Vedran Ćorluka'),
      L('CB', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('RB', 'Ренат Янбаев', 'Renat Yanbaev'),
      L('LM', 'Дмитрий Лоськов', 'Dmitri Loskov'),
      L('CM', 'Игорь Денисов', 'Igor Denisov'),
      L('CM', 'Гжегож Крыховяк', 'Grzegorz Krychowiak'),
      L('RM', 'Алексей Миранчук', 'Aleksei Miranchuk'),
      L('ST', 'Дмитрий Сычёв', 'Dmitri Sychev'),
      L('ST', 'Джефферсон Фарфан', 'Jefferson Farfán'),
    ],
    bench: [
      L('GK', 'Сергей Овчинников', 'Sergei Ovchinnikov'),
      L('DF', 'Вадим Евсеев', 'Vadim Evseev'),
      L('DF', 'Соломон Кверквелия', 'Solomon Kvirkvelia'),
      L('MF', 'Динияр Билялетдинов', 'Diniyar Bilyaletdinov'),
      L('MF', 'Мануэл Фернандеш', 'Manuel Fernandes'),
      L('FW', 'Роман Павлюченко', 'Roman Pavlyuchenko'),
      L('FW', 'Фёдор Смолов', 'Fyodor Smolov'),
    ],
  },
  'Спартак (Москва)': {
    start: [
      L('GK', 'Артём Ребров', 'Artem Rebrov'),
      L('LB', 'Дмитрий Комбаров', 'Dmitri Kombarov'),
      L('CB', 'Георгий Джикия', 'Georgi Dzhikia'),
      L('CB', 'Сердар Таски', 'Serdar Tasci'),
      L('RB', 'Андрей Ещенко', 'Andrey Yeshchenko'),
      L('LM', 'Квинси Промес', 'Quincy Promes'),
      L('CM', 'Роман Зобнин', 'Roman Zobnin'),
      L('CM', 'Денис Глушаков', 'Denis Glushakov'),
      L('RM', 'Александр Самедов', 'Aleksandr Samedov'),
      L('ST', 'Веллитон', 'Welliton'),
      L('ST', 'Луис Адриано', 'Luís Adriano'),
    ],
    bench: [
      L('GK', 'Александр Максименко', 'Aleksandr Maksimenko'),
      L('DF', 'Эммануэль Маммана', 'Emanuel Mammana'),
      L('DF', 'Илья Кутепов', 'Ilya Kutepov'),
      L('MF', 'Эсекиэль Барко', 'Esequiel Barco'),
      L('MF', 'Аяз Гулиев', 'Ayaz Guliev'),
      L('FW', 'Зе Луиш', 'Zé Luís'),
      L('FW', 'Лукас Барриос', 'Lucas Barrios'),
    ],
  },
  'Динамо (Москва)': {
    start: [
      L('GK', 'Владимир Габулов', 'Vladimir Gabulov'),
      L('LB', 'Кирилл Комбаров', 'Kirill Kombarov'),
      L('CB', 'Шунейдер', 'Shuneyder'),
      L('CB', 'Тони Шуньич', 'Toni Šunjić'),
      L('RB', 'Григорий Морозов', 'Grigori Morozov'),
      L('LM', 'Юсупов', 'Yusupov'),
      L('CM', 'Чарлес Каборе', 'Charles Kaboré'),
      L('CM', 'Артур Юсупов', 'Artur Yusupov'),
      L('RM', 'Александр Ташаев', 'Aleksandr Tashaev'),
      L('ST', 'Фёдор Смолов', 'Fyodor Smolov'),
      L('ST', 'Кевин Кураньи', 'Kevin Kurányi'),
    ],
    bench: [
      L('GK', 'Антон Шунин', 'Anton Shunin'),
      L('DF', 'Александр Бюттнер', 'Alexander Büttner'),
      L('DF', 'Дмитрий Белоруков', 'Dmitri Belorukov'),
      L('MF', 'Игорь Денисов', 'Igor Denisov'),
      L('MF', 'Алексей Ионов', 'Aleksei Ionov'),
      L('FW', 'Силваниус Доминик', 'Silvanus Dominic'),
      L('FW', 'Вячеслав Грулёв', 'Vyacheslav Grulyov'),
    ],
  },
  'Рубин (Казань)': {
    start: [
      L('GK', 'Сергей Рыжиков', 'Sergey Ryzhikov'),
      L('LB', 'Кристиан Ансальди', 'Cristian Ansaldi'),
      L('CB', 'Роман Шаронов', 'Roman Sharonov'),
      L('CB', 'Цезарь Навас', 'César Navas'),
      L('RB', 'Олег Кузьмин', 'Oleg Kuzmin'),
      L('LM', 'Гёкдениз Карадениз', 'Gökdeniz Karadeniz'),
      L('CM', 'Бибрас Натхо', 'Bibras Natkho'),
      L('CM', 'Алан Касаев', 'Alan Kasaev'),
      L('RM', 'Карлос Эдуардо', 'Carlos Eduardo'),
      L('ST', 'Александр Бухаров', 'Aleksandr Bukharov'),
      L('ST', 'Нельсон Аэдо Вальдес', 'Nelson Haedo Valdez'),
    ],
    bench: [
      L('GK', 'Роман Березовский', 'Roman Berezovsky'),
      L('DF', 'Виталий Калешин', 'Vitali Kaleshin'),
      L('DF', 'Лаша Салуквадзе', 'Lasha Salukvadze'),
      L('MF', 'Максим Левицкий', 'Maksim Levitsky'),
      L('MF', 'Роман Ерёменко', 'Roman Eremenko'),
      L('FW', 'Владимир Дядюн', 'Vladimir Dyadyun'),
      L('FW', 'Сердар Азмун', 'Sardar Azmoun'),
    ],
  },
  'Ростов (Ростов-на-Дону)': {
    start: [
      L('GK', 'Стипе Плетикоса', 'Stipe Pletikosa'),
      L('LB', 'Милош Крушчич', 'Miloš Kruščić'),
      L('CB', 'Мэттью Бут', 'Matthew Booth'),
      L('CB', 'Цезарь Навас', 'César Navas'),
      L('RB', 'Виталий Дьяков', 'Vitali Dyakov'),
      L('LM', 'Тимофей Калачёв', 'Timofei Kalachev'),
      L('CM', 'Александр Гацкан', 'Alexandr Gatskan'),
      L('CM', 'Кристиан Нобоа', 'Christian Noboa'),
      L('RM', 'Дмитрий Полоз', 'Dmitri Poloz'),
      L('ST', 'Артём Дзюба', 'Artem Dzyuba'),
      L('ST', 'Кантемир Берхамов', 'Kantemir Berkhamov'),
    ],
    bench: [
      L('GK', 'Сергей Песьяков', 'Sergey Pesyakov'),
      L('DF', 'Джордж Балашов', 'George Balashov'),
      L('DF', 'Виталий Денисов', 'Vitali Denisov'),
      L('MF', 'Хорен Байрамян', 'Khoren Bayramyan'),
      L('MF', 'Александр Саплинов', 'Alexander Saplinov'),
      L('FW', 'Дмитрий Кириченко', 'Dmitri Kirichenko'),
      L('FW', 'Александр Бухаров', 'Aleksandr Bukharov'),
    ],
  },
  'Крылья Советов (Самара)': {
    start: [
      L('GK', 'Эдуардо Лобос', 'Eduardo Lobos'),
      L('LB', 'Юрий Горшков', 'Yury Gorshkov'),
      L('CB', 'Мэттью Бут', 'Matthew Booth'),
      L('CB', 'Денис Колодин', 'Denis Kolodin'),
      L('RB', 'Александр Анюков', 'Aleksandr Anyukov'),
      L('LM', 'Андрей Каряка', 'Andrei Karyaka'),
      L('CM', 'Фернандо Костанца', 'Fernando Costanza'),
      L('CM', 'Жозе Иваналдо де Соуза', 'José Ivanildo de Souza'),
      L('RM', 'Андрей Тихонов', 'Andrei Tikhonov'),
      L('ST', 'Иван Сергеев', 'Ivan Sergeev'),
      L('ST', 'Сергей Корниленко', 'Sergei Kornilenko'),
    ],
    bench: [
      L('GK', 'Сергей Рыжиков', 'Sergey Ryzhikov'),
      L('DF', 'Александр Солдатенков', 'Aleksandr Soldatenkov'),
      L('DF', 'Сергей Божин', 'Sergey Bozhin'),
      L('MF', 'Владислав Игнатьев', 'Vladislav Ignatyev'),
      L('MF', 'Антон Бобёр', 'Anton Bobyor'),
      L('FW', 'Александр Соболев', 'Aleksandr Sobolev'),
      L('FW', 'Евгений Савин', 'Evgeny Savin'),
    ],
  },
  'Ахмат (Грозный)': {
    start: [
      L('GK', 'Гиорги Шелия', 'Giorgi Shelia'),
      L('LB', 'Мирослав Богосавац', 'Miroslav Bogosavac'),
      L('CB', 'Вилькер Анхель', 'Wilker Ángel'),
      L('CB', 'Андрей Семёнов', 'Andrei Semyonov'),
      L('RB', 'Ризван Уциев', 'Rizvan Utsiev'),
      L('LM', 'Бернард Бериша', 'Bernard Berisha'),
      L('CM', 'Олег Иванов', 'Oleg Ivanov'),
      L('CM', 'Исмаэл Силва', 'Ismael Silva'),
      L('RM', 'Мохамед Конате', 'Mohamed Konaté'),
      L('ST', 'Аблай Мбенг', 'Ablaye Mbengue'),
      L('ST', 'Андрес Понсе', 'Andrés Ponce'),
    ],
    bench: [
      L('GK', 'Александр Филиппов', 'Aleksandr Filippov'),
      L('DF', 'Зоран Нижич', 'Zoran Nižić'),
      L('DF', 'Максим Ненахов', 'Maksim Nenakhov'),
      L('MF', 'Даниил Уткин', 'Daniil Utkin'),
      L('MF', 'Артур Тимофеев', 'Artur Timofeev'),
      L('FW', 'Георгий Мелкадзе', 'Georgi Melkadze'),
      L('FW', 'Гамид Агаларов', 'Gamid Agalarov'),
    ],
  },
  'Краснодар (Краснодар)': {
    start: [
      L('GK', 'Андрей Дикань', 'Andriy Dikan'),
      L('LB', 'Сергей Петров', 'Sergey Petrov'),
      L('CB', 'Андреас Гранквист', 'Andreas Granqvist'),
      L('CB', 'Рагнар Сигурдссон', 'Ragnar Sigurðsson'),
      L('RB', 'Александр Мартынович', 'Aleksandr Martynovich'),
      L('LM', 'Марат Измайлов', 'Marat Izmailov'),
      L('CM', 'Юрий Газинский', 'Yuri Gazinsky'),
      L('CM', 'Шарль Каборе', 'Charles Kaboré'),
      L('RM', 'Рикардо Лаборде', 'Ricardo Laborde'),
      L('ST', 'Фёдор Смолов', 'Fyodor Smolov'),
      L('ST', 'Ари', 'Ari'),
    ],
    bench: [
      L('GK', 'Матвей Сафонов', 'Matvey Safonov'),
      L('DF', 'Кристиан Рамирес', 'Christian Ramírez'),
      L('DF', 'Виталий Калешин', 'Vitali Kaleshin'),
      L('MF', 'Маурисио Перейра', 'Mauricio Pereyra'),
      L('MF', 'Роман Широков', 'Roman Shirokov'),
      L('FW', 'Виктор Классон', 'Viktor Claesson'),
      L('FW', 'Джон Кордоба', 'Jhon Córdoba'),
    ],
  },
  'Амкар (Пермь)': {
    start: [
      L('GK', 'Сергей Нарубин', 'Sergey Narubin'),
      L('LB', 'Дмитрий Белоруков', 'Dmitri Belorukov'),
      L('CB', 'Дмитрий Михеев', 'Dmitri Mikheev'),
      L('CB', 'Виталий Гришин', 'Vitali Grishin'),
      L('RB', 'Заурбек Плиев', 'Zaurbek Pliev'),
      L('LM', 'Константин Зырянов', 'Konstantin Zyryanov'),
      L('CM', 'Александр Коломейцев', 'Aleksandr Kolomeytsev'),
      L('CM', 'Георгий Пеев', 'Georgi Peev'),
      L('RM', 'Сергей Волков', 'Sergei Volkov'),
      L('ST', 'Александр Прудников', 'Aleksandr Prudnikov'),
      L('ST', 'Мартин Кушев', 'Martin Kushev'),
    ],
    bench: [
      L('GK', 'Дмитрий Хомич', 'Dmitri Khomich'),
      L('DF', 'Иван Черенчиков', 'Ivan Cherenchikov'),
      L('DF', 'Михал Пападопулос', 'Michal Papadopulos'),
      L('MF', 'Благой Георгиев', 'Blagoy Georgiev'),
      L('MF', 'Никита Салтыков', 'Nikita Saltykov'),
      L('FW', 'Артур Рябокобыленко', 'Artur Ryabokobylenko'),
      L('FW', 'Ян Голенда', 'Yan Golenda'),
    ],
  },
  'Сатурн (Раменское)': {
    start: [
      L('GK', 'Антонин Кински', 'Antonín Kinský'),
      L('LB', 'Алексей Игонин', 'Aleksei Igonin'),
      L('CB', 'Александр Шешуков', 'Aleksandr Sheshukov'),
      L('CB', 'Джордже Йокич', 'Đorđe Jokić'),
      L('RB', 'Роман Шишкин', 'Roman Shishkin'),
      L('LM', 'Петр Немов', 'Pyotr Nemov'),
      L('CM', 'Максим Ромащенко', 'Maksim Romaschenko'),
      L('CM', 'Чарлес Каборе', 'Charles Kaboré'),
      L('RM', 'Андрей Каряка', 'Andrei Karyaka'),
      L('ST', 'Дмитрий Кириченко', 'Dmitri Kirichenko'),
      L('ST', 'Мартин Йиранек', 'Martin Jiránek'),
    ],
    bench: [
      L('GK', 'Евгений Корнюхин', 'Evgeni Kornyukhin'),
      L('DF', 'Сергей Будылин', 'Sergey Budylin'),
      L('DF', 'Милан Йованович', 'Milan Jovanović'),
      L('MF', 'Иржи Ярошик', 'Jiří Jarošík'),
      L('MF', 'Висенте', 'Vicente'),
      L('FW', 'Александр Катасон', 'Aleksandr Katason'),
      L('FW', 'Томаш Сокол', 'Tomáš Sokol'),
    ],
  },
  'ФК Москва (Москва)': {
    start: [
      L('GK', 'Юрий Жевнов', 'Yuri Zhevnov'),
      L('LB', 'Кирилл Орлов', 'Kirill Orlov'),
      L('CB', 'Дмитрий Годунок', 'Dmitri Godunok'),
      L('CB', 'Горан Мазанов', 'Goran Mazanov'),
      L('RB', 'Александр Шешуков', 'Aleksandr Sheshukov'),
      L('LM', 'Дмитрий Кириченко', 'Dmitri Kirichenko'),
      L('CM', 'Артём Ребров', 'Artem Rebrov'),
      L('CM', 'Сергей Кормильцев', 'Sergei Kormiltsev'),
      L('RM', 'Александр Самедов', 'Aleksandr Samedov'),
      L('ST', 'Дмитрий Сычёв', 'Dmitri Sychev'),
      L('ST', 'Александр Кержаков', 'Aleksandr Kerzhakov'),
    ],
    bench: [
      L('GK', 'Александр Будаков', 'Aleksandr Budakov'),
      L('DF', 'Александр Шешуков', 'Aleksandr Sheshukov'),
      L('DF', 'Радослав Батак', 'Radoslav Batak'),
      L('MF', 'Максим Лопоухов', 'Maksim Lopoukhov'),
      L('MF', 'Александр Даншев', 'Aleksandr Danshev'),
      L('FW', 'Андрей Стрельцов', 'Andrei Streltsov'),
      L('FW', 'Майкон Маркес', 'Maicon Marques'),
    ],
  },
  'Анжи (Махачкала)': {
    start: [
      L('GK', 'Евгений Помазан', 'Evgeni Pomazan'),
      L('LB', 'Юрий Жирков', 'Yuri Zhirkov'),
      L('CB', 'Эвертон', 'Everton'),
      L('CB', 'Артур Малофеев', 'Artur Malofeev'),
      L('RB', 'Расул Тагирбеков', 'Rasul Tagirbekov'),
      L('LM', 'Абдул-Рашид Садулаев', 'Abdul-Rashid Sadulayev'),
      L('CM', 'Шамиль Лахиялов', 'Shamil Lakhiyalov'),
      L('CM', 'Али Гаджибеков', 'Ali Gadzhibekov'),
      L('RM', 'Марцин Ковальчик', 'Marcin Kowalczyk'),
      L('ST', 'Самуэль Это’о', 'Samuel Eto’o'),
      L('ST', 'Ласина Траоре', 'Lacina Traoré'),
    ],
    bench: [
      L('GK', 'Александр Криворучко', 'Aleksandr Krivoruchko'),
      L('DF', 'Мурад Ханмурзаев', 'Murad Khanmurzaev'),
      L('DF', 'Залимхан Юсупов', 'Zalimkhan Yusupov'),
      L('MF', 'Олег Шатов', 'Oleg Shatov'),
      L('MF', 'Жусилей', 'Jucilei'),
      L('FW', 'Диего Тарделли', 'Diego Tardelli'),
      L('FW', 'Ибрагим Гасанбеков', 'Ibragim Gasanbekov'),
    ],
  },
  'Урал (Екатеринбург)': {
    start: [
      L('GK', 'Олег Баклов', 'Oleg Baklov'),
      L('LB', 'Эрик Бикфалви', 'Eric Bicfalvi'),
      L('CB', 'Илья Кутепов', 'Ilya Kutepov'),
      L('CB', 'Артём Мамин', 'Artyom Mamin'),
      L('RB', 'Герсон Асеведо', 'Gerson Acevedo'),
      L('LM', 'Юрий Матвеев', 'Yuri Matveev'),
      L('CM', 'Андрей Егорычев', 'Andrey Egorychev'),
      L('CM', 'Даниел Мишкич', 'Daniel Miškić'),
      L('RM', 'Кантемир Берхамов', 'Kantemir Berkhamov'),
      L('ST', 'Павел Погребняк', 'Pavel Pogrebnyak'),
      L('ST', 'Юрий Железнов', 'Yuri Zheleznov'),
    ],
    bench: [
      L('GK', 'Николай Заболотный', 'Nikolay Zabolotny'),
      L('DF', 'Сильвие Бегич', 'Silvije Begić'),
      L('DF', 'Илья Зуев', 'Ilya Zuev'),
      L('MF', 'Александр Щербаков', 'Aleksandr Shcherbakov'),
      L('MF', 'Вячеслав Караваев', 'Vyacheslav Karavaev'),
      L('FW', 'Владимир Ильин', 'Vladimir Ilyin'),
      L('FW', 'Роман Павлюченко', 'Roman Pavlyuchenko'),
    ],
  },
}
