import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

export const CLUB_LINEUPS_PART1: Record<string, ClubLineupData> = {
  Arsenal: {
    start: [
      L('GK', 'Йенс Леманн', 'Jens Lehmann'),
      L('LB', 'Эшли Коул', 'Ashley Cole'),
      L('CB', 'Сол Кэмпбелл', 'Sol Campbell'),
      L('CB', 'Тони Адамс', 'Tony Adams'),
      L('RB', 'Лорен', 'Lauren'),
      L('LM', 'Робер Пирес', 'Robert Pires'),
      L('CM', 'Патрик Виейра', 'Patrick Vieira'),
      L('CM', 'Фредди Юнгберг', 'Freddie Ljungberg'),
      L('RM', 'Букайо Сака', 'Bukayo Saka'),
      L('ST', 'Тьерри Анри', 'Thierry Henry'),
      L('ST', 'Деннис Бергкамп', 'Dennis Bergkamp'),
    ],
    bench: [
      L('GK', 'Давид Симен', 'David Seaman'),
      L('DF', 'Гаэль Клиши', 'Gaël Clichy'),
      L('DF', 'Мартин Киоун', 'Martin Keown'),
      L('MF', 'Рэй Парлор', 'Ray Parlour'),
      L('MF', 'Арон Рэмзи', 'Aaron Ramsey'),
      L('FW', 'Иан Райт', 'Ian Wright'),
      L('FW', 'Робин ван Перси', 'Robin van Persie'),
    ],
  },
  'Atlético Madrid': {
    start: [
      L('GK', 'Ян Облак', 'Jan Oblak'),
      L('LB', 'Филипе Луис', 'Filipe Luís'),
      L('CB', 'Диего Годин', 'Diego Godín'),
      L('CB', 'Жозе Мария Хименес', 'José María Giménez'),
      L('RB', 'Хуанфран', 'Juanfran'),
      L('LM', 'Арда Туран', 'Arda Turan'),
      L('CM', 'Габи', 'Gabi'),
      L('CM', 'Коке', 'Koke'),
      L('RM', 'Сауль Ньигес', 'Saúl Ñíguez'),
      L('ST', 'Антуан Гризманн', 'Antoine Griezmann'),
      L('ST', 'Радамель Фалькао', 'Radamel Falcao'),
    ],
    bench: [
      L('GK', 'Тибо Куртуа', 'Thibaut Courtois'),
      L('DF', 'Кристиан Ансальди', 'Cristian Ansaldi'),
      L('DF', 'Луис Переа', 'Luis Perea'),
      L('MF', 'Тиагу Мендеш', 'Tiago Mendes'),
      L('MF', 'Маркос Льоренте', 'Marcos Llorente'),
      L('FW', 'Диего Коста', 'Diego Costa'),
      L('FW', 'Серхио Агуэро', 'Sergio Agüero'),
    ],
  },
  Ajax: {
    start: [
      L('GK', 'Эдвин ван дер Сар', 'Edwin van der Sar'),
      L('LB', 'Дейли Блинд', 'Daley Blind'),
      L('CB', 'Маттейс де Лигт', 'Matthijs de Ligt'),
      L('CB', 'Лисандро Мартинес', 'Lisandro Martínez'),
      L('RB', 'Нуссаир Мазрауи', 'Noussair Mazraoui'),
      L('LM', 'Хаким Зиеш', 'Hakim Ziyech'),
      L('CM', 'Френки де Йонг', 'Frenkie de Jong'),
      L('CM', 'Душан Тадич', 'Dušan Tadić'),
      L('RM', 'Райан Гравенберх', 'Ryan Gravenberch'),
      L('ST', 'Клас-Ян Хюнтелар', 'Klaas-Jan Huntelaar'),
      L('ST', 'Луис Суарес', 'Luis Suárez'),
    ],
    bench: [
      L('GK', 'Мартен Стекеленбург', 'Maarten Stekelenburg'),
      L('DF', 'Кристиан Киву', 'Cristian Chivu'),
      L('DF', 'Яп Стам', 'Jaap Stam'),
      L('MF', 'Стивен Бергвейн', 'Steven Bergwijn'),
      L('MF', 'Юрриен Тимбер', 'Jurriën Timber'),
      L('FW', 'Рафаэл ван дер Варт', 'Rafael van der Vaart'),
      L('FW', 'Златан Ибрагимович', 'Zlatan Ibrahimović'),
    ],
  },
  Barcelona: {
    start: [
      L('GK', 'Виктор Вальдес', 'Víctor Valdés'),
      L('LB', 'Жорди Альба', 'Jordi Alba'),
      L('CB', 'Карлес Пуйоль', 'Carles Puyol'),
      L('CB', 'Жерар Пике', 'Gerard Piqué'),
      L('RB', 'Дани Алвес', 'Dani Alves'),
      L('LM', 'Роналдиньо', 'Ronaldinho'),
      L('CM', 'Хави', 'Xavi'),
      L('CM', 'Андрес Иньеста', 'Andrés Iniesta'),
      L('RM', 'Лионель Месси', 'Lionel Messi'),
      L('ST', 'Луис Суарес', 'Luis Suárez'),
      L('ST', 'Самуэль Это’О', 'Samuel Eto’o'),
    ],
    bench: [
      L('GK', 'Марк-Андре тер Стеген', 'Marc-André ter Stegen'),
      L('DF', 'Эрик Абидаль', 'Éric Abidal'),
      L('DF', 'Рафаэль Маркес', 'Rafael Márquez'),
      L('MF', 'Чави Алонсо', 'Xabi Alonso'),
      L('MF', 'Иван Ракитич', 'Ivan Rakitić'),
      L('FW', 'Неймар', 'Neymar'),
      L('FW', 'Давид Вилья', 'David Villa'),
    ],
  },
  'Bayer Leverkusen': {
    start: [
      L('GK', 'Бернд Лено', 'Bernd Leno'),
      L('LB', 'Венделл', 'Wendell'),
      L('CB', 'Йонатан Та', 'Jonathan Tah'),
      L('CB', 'Эдмон Тапсоба', 'Edmond Tapsoba'),
      L('RB', 'Джереми Фримпонг', 'Jeremie Frimpong'),
      L('LM', 'Флориан Вирц', 'Florian Wirtz'),
      L('CM', 'Кай Хаверц', 'Kai Havertz'),
      L('CM', 'Чарлес Арангис', 'Charles Aránguiz'),
      L('RM', 'Мусса Диаби', 'Moussa Diaby'),
      L('ST', 'Сон Хын Мин', 'Son Heung-min'),
      L('ST', 'Штефан Кисслинг', 'Stefan Kießling'),
    ],
    bench: [
      L('GK', 'Лукаш Градецки', 'Lukas Hradecky'),
      L('DF', 'Гонсало Кастро', 'Gonzalo Castro'),
      L('DF', 'Ларс Бендер', 'Lars Bender'),
      L('MF', 'Майкл Баллак', 'Michael Ballack'),
      L('MF', 'Артуро Видаль', 'Arturo Vidal'),
      L('FW', 'Хавьер Эрнандес', 'Javier Hernández'),
      L('FW', 'Димитар Бербатов', 'Dimitar Berbatov'),
    ],
  },
  'Bayern Munich': {
    start: [
      L('GK', 'Мануэль Нойер', 'Manuel Neuer'),
      L('LB', 'Филипп Лам', 'Philipp Lahm'),
      L('CB', 'Матс Хуммельс', 'Mats Hummels'),
      L('CB', 'Жером Боатенг', 'Jérôme Boateng'),
      L('RB', 'Вилли Саньоль', 'Willy Sagnol'),
      L('LM', 'Франк Рибери', 'Franck Ribéry'),
      L('CM', 'Бастиан Швайнштайгер', 'Bastian Schweinsteiger'),
      L('CM', 'Михаэль Баллак', 'Michael Ballack'),
      L('RM', 'Арьен Роббен', 'Arjen Robben'),
      L('ST', 'Роберт Левандовски', 'Robert Lewandowski'),
      L('ST', 'Томас Мюллер', 'Thomas Müller'),
    ],
    bench: [
      L('GK', 'Оливер Кан', 'Oliver Kahn'),
      L('DF', 'Давид Алаба', 'David Alaba'),
      L('DF', 'Лусио', 'Lucio'),
      L('MF', 'Тони Кроос', 'Toni Kroos'),
      L('MF', 'Оуэн Харгривз', 'Owen Hargreaves'),
      L('FW', 'Марио Гомес', 'Mario Gomez'),
      L('FW', 'Рой Макай', 'Roy Makaay'),
    ],
  },
  'Borussia Dortmund': {
    start: [
      L('GK', 'Роман Вайденфеллер', 'Roman Weidenfeller'),
      L('LB', 'Марсель Шмельцер', 'Marcel Schmelzer'),
      L('CB', 'Матс Хуммельс', 'Mats Hummels'),
      L('CB', 'Невен Суботич', 'Neven Subotić'),
      L('RB', 'Лукаш Пищек', 'Łukasz Piszczek'),
      L('LM', 'Марко Ройс', 'Marco Reus'),
      L('CM', 'Илкай Гюндоган', 'İlkay Gündoğan'),
      L('CM', 'Джуд Беллингем', 'Jude Bellingham'),
      L('RM', 'Якуб Блащиковски', 'Jakub Błaszczykowski'),
      L('ST', 'Роберт Левандовски', 'Robert Lewandowski'),
      L('ST', 'Пьер-Эмерик Обамеянг', 'Pierre-Emerick Aubameyang'),
    ],
    bench: [
      L('GK', 'Грегор Кобель', 'Gregor Kobel'),
      L('DF', 'Мануэль Аканджи', 'Manuel Akanji'),
      L('DF', 'Эрик Дурм', 'Erik Durm'),
      L('MF', 'Нури Шахин', 'Nuri Şahin'),
      L('MF', 'Шиндзи Кагава', 'Shinji Kagawa'),
      L('FW', 'Эрлинг Холанн', 'Erling Haaland'),
      L('FW', 'Лукас Барриос', 'Lucas Barrios'),
    ],
  },
  Chelsea: {
    start: [
      L('GK', 'Петр Чех', 'Petr Čech'),
      L('LB', 'Эшли Коул', 'Ashley Cole'),
      L('CB', 'Джон Терри', 'John Terry'),
      L('CB', 'Рикарду Карвалью', 'Ricardo Carvalho'),
      L('RB', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('LM', 'Эден Азар', 'Eden Hazard'),
      L('CM', 'Фрэнк Лэмпард', 'Frank Lampard'),
      L('CM', 'Клод Макелеле', 'Claude Makélélé'),
      L('RM', 'Дидье Дрогба', 'Didier Drogba'),
      L('ST', 'Эйдур Гудьонсен', 'Eiður Guðjohnsen'),
      L('ST', 'Николя Анелька', 'Nicolas Anelka'),
    ],
    bench: [
      L('GK', 'Тибо Куртуа', 'Thibaut Courtois'),
      L('DF', 'Сесар Аспиликуэта', 'César Azpilicueta'),
      L('DF', 'Гари Кэхилл', 'Gary Cahill'),
      L('MF', 'Майкл Эссьен', 'Michael Essien'),
      L('MF', 'Хуан Мата', 'Juan Mata'),
      L('FW', 'Фернандо Торрес', 'Fernando Torres'),
      L('FW', 'Саломон Калу', 'Salomon Kalou'),
    ],
  },
}
