import { lineupLine as L } from './bestLineupHelpers'
import type { ClubLineupData } from './clubLineupTypes'

export const CLUB_LINEUPS_PART2: Record<string, ClubLineupData> = {
  'CSKA Moscow': {
    start: [
      L('GK', 'Игорь Акинфеев', 'Igor Akinfeev'),
      L('LB', 'Юрий Жирков', 'Yuri Zhirkov'),
      L('CB', 'Сергей Игнашевич', 'Sergei Ignashevich'),
      L('CB', 'Алексей Березуцкий', 'Aleksei Berezutski'),
      L('RB', 'Марио Фернандес', 'Mário Fernandes'),
      L('LM', 'Алан Дзагоев', 'Alan Dzagoev'),
      L('CM', 'Понтус Вернблум', 'Pontus Wernbloom'),
      L('CM', 'Милош Красич', 'Miloš Krasić'),
      L('RM', 'Ахмед Муса', 'Ahmed Musa'),
      L('ST', 'Вагнер Лав', 'Vágner Love'),
      L('ST', 'Сейду Думбия', 'Seydou Doumbia'),
    ],
    bench: [
      L('GK', 'Владимир Габулов', 'Vladimir Gabulov'),
      L('DF', 'Георгий Щенников', 'Georgi Shchennikov'),
      L('DF', 'Вадим Березуцкий', 'Vadim Berezutski'),
      L('MF', 'Роман Еременко', 'Roman Eremenko'),
      L('MF', 'Никола Влашич', 'Nikola Vlašić'),
      L('FW', 'Ивица Олич', 'Ivica Olić'),
      L('FW', 'Томаш Нецид', 'Tomáš Necid'),
    ],
  },
  Fenerbahçe: {
    start: [
      L('GK', 'Рюштю Речбер', 'Rüştü Reçber'),
      L('LB', 'Джанер Эркин', 'Caner Erkin'),
      L('CB', 'Диего Лугано', 'Diego Lugano'),
      L('CB', 'Симон Кьер', 'Simon Kjær'),
      L('RB', 'Гёкхан Гёнюл', 'Gökhan Gönül'),
      L('LM', 'Алекс де Соуза', 'Alex de Souza'),
      L('CM', 'Эмре Белёзоглу', 'Emre Belözoğlu'),
      L('CM', 'Мехмет Топал', 'Mehmet Topal'),
      L('RM', 'Мирослав Стох', 'Miroslav Stoch'),
      L('ST', 'Робин ван Перси', 'Robin van Persie'),
      L('ST', 'Пьер Вебо', 'Pierre Webo'),
    ],
    bench: [
      L('GK', 'Волкан Демирель', 'Volkan Demirel'),
      L('DF', 'Роберто Карлос', 'Roberto Carlos'),
      L('DF', 'Кристиан Барони', 'Cristian Baroni'),
      L('MF', 'Дирк Кёйт', 'Dirk Kuyt'),
      L('MF', 'Стивен Ленс', 'Steven Lens'),
      L('FW', 'Фернандао', 'Fernandão'),
      L('FW', 'Семих Шентюрк', 'Semih Şentürk'),
    ],
  },
  Galatasaray: {
    start: [
      L('GK', 'Фернандо Муслера', 'Fernando Muslera'),
      L('LB', 'Хакан Балта', 'Hakan Balta'),
      L('CB', 'Семих Кая', 'Semih Kaya'),
      L('CB', 'Сервет Четин', 'Servet Çetin'),
      L('RB', 'Сабри Сарыоглу', 'Sabri Sarıoğlu'),
      L('LM', 'Арда Туран', 'Arda Turan'),
      L('CM', 'Уэсли Снейдер', 'Wesley Sneijder'),
      L('CM', 'Сельчук Инан', 'Selçuk İnan'),
      L('RM', 'Хамит Алтынтоп', 'Hamit Altıntop'),
      L('ST', 'Дидье Дрогба', 'Didier Drogba'),
      L('ST', 'Бурак Йылмаз', 'Burak Yılmaz'),
    ],
    bench: [
      L('GK', 'Айкут Эрчетин', 'Aykut Erçetin'),
      L('DF', 'Эмре Гюнгёр', 'Emre Güngör'),
      L('DF', 'Джейхун Гюльселам', 'Ceyhun Gülselam'),
      L('MF', 'Линкольн', 'Lincoln'),
      L('MF', 'Жуан Алвес', 'João Alves'),
      L('FW', 'Милан Барош', 'Milan Baroš'),
      L('FW', 'Хакан Шукюр', 'Hakan Şükür'),
    ],
  },
  Internazionale: {
    start: [
      L('GK', 'Жулио Сезар', 'Júlio César'),
      L('LB', 'Хавир Санетти', 'Javier Zanetti'),
      L('CB', 'Вальтер Самуэль', 'Walter Samuel'),
      L('CB', 'Иван Кордоба', 'Iván Córdoba'),
      L('RB', 'Майкон', 'Maicon'),
      L('LM', 'Уэсли Снейдер', 'Wesley Sneijder'),
      L('CM', 'Эстебан Камбьяссо', 'Esteban Cambiasso'),
      L('CM', 'Деян Станкович', 'Dejan Stanković'),
      L('RM', 'Луиш Фигу', 'Luís Figo'),
      L('ST', 'Златан Ибрагимович', 'Zlatan Ibrahimović'),
      L('ST', 'Роналдо', 'Ronaldo'),
    ],
    bench: [
      L('GK', 'Франческо Тольдо', 'Francesco Toldo'),
      L('DF', 'Марко Матерацци', 'Marco Materazzi'),
      L('DF', 'Кристиан Киву', 'Cristian Chivu'),
      L('MF', 'Кристиан Эриксен', 'Christian Eriksen'),
      L('MF', 'Фредерик Гуарин', 'Fredy Guarín'),
      L('FW', 'Эрнан Креспо', 'Hernán Crespo'),
      L('FW', 'Диего Милито', 'Diego Milito'),
    ],
  },
  Juventus: {
    start: [
      L('GK', 'Джанлуиджи Буффон', 'Gianluigi Buffon'),
      L('LB', 'Джорджо Кьеллини', 'Giorgio Chiellini'),
      L('CB', 'Фабио Каннаваро', 'Fabio Cannavaro'),
      L('CB', 'Леонардо Бонуччи', 'Leonardo Bonucci'),
      L('RB', 'Лилиан Тюрам', 'Lilian Thuram'),
      L('LM', 'Павел Недвед', 'Pavel Nedvěd'),
      L('CM', 'Андреа Пирло', 'Andrea Pirlo'),
      L('CM', 'Артуро Видаль', 'Arturo Vidal'),
      L('RM', 'Мауро Каморанези', 'Mauro Camoranesi'),
      L('ST', 'Алессандро Дель Пьеро', 'Alessandro Del Piero'),
      L('ST', 'Давид Трезеге', 'David Trezeguet'),
    ],
    bench: [
      L('GK', 'Марко Сторари', 'Marco Storari'),
      L('DF', 'Андреа Бардзальи', 'Andrea Barzagli'),
      L('DF', 'Федерико Кьеза', 'Federico Chiesa'),
      L('MF', 'Клаудио Маркизио', 'Claudio Marchisio'),
      L('MF', 'Пол Погба', 'Paul Pogba'),
      L('FW', 'Филиппо Индзаги', 'Filippo Inzaghi'),
      L('FW', 'Криштиану Роналду', 'Cristiano Ronaldo'),
    ],
  },
  'Leicester City': {
    start: [
      L('GK', 'Каспер Шмейхель', 'Kasper Schmeichel'),
      L('LB', 'Кристиан Фукс', 'Christian Fuchs'),
      L('CB', 'Уэс Морган', 'Wes Morgan'),
      L('CB', 'Роберт Хут', 'Robert Huth'),
      L('RB', 'Дэнни Симпсон', 'Danny Simpson'),
      L('LM', 'Марк Олбрайтон', 'Marc Albrighton'),
      L('CM', 'Н’Голо Канте', 'N’Golo Kanté'),
      L('CM', 'Дэнни Дринкуотер', 'Danny Drinkwater'),
      L('RM', 'Рияд Марез', 'Riyad Mahrez'),
      L('ST', 'Джейми Варди', 'Jamie Vardy'),
      L('ST', 'Синдзи Окадзаки', 'Shinji Okazaki'),
    ],
    bench: [
      L('GK', 'Эльдин Якупович', 'Eldin Jakupović'),
      L('DF', 'Харри Магуайр', 'Harry Maguire'),
      L('DF', 'Джонни Эванс', 'Jonny Evans'),
      L('MF', 'Юрий Тилеманс', 'Youri Tielemans'),
      L('MF', 'Деннис Прат', 'Dennis Praet'),
      L('FW', 'Леонардо Ульоа', 'Leonardo Ulloa'),
      L('FW', 'Ислам Слимани', 'Islam Slimani'),
    ],
  },
  Liverpool: {
    start: [
      L('GK', 'Алиссон Бекер', 'Alisson Becker'),
      L('LB', 'Энди Робертсон', 'Andy Robertson'),
      L('CB', 'Вирджил ван Дейк', 'Virgil van Dijk'),
      L('CB', 'Джейми Каррагер', 'Jamie Carragher'),
      L('RB', 'Трент Александер-Арнольд', 'Trent Alexander-Arnold'),
      L('LM', 'Садио Мане', 'Sadio Mané'),
      L('CM', 'Стивен Джеррард', 'Steven Gerrard'),
      L('CM', 'Джаби Алонсо', 'Xabi Alonso'),
      L('RM', 'Мохамед Салах', 'Mohamed Salah'),
      L('ST', 'Луис Суарес', 'Luis Suárez'),
      L('ST', 'Фернандо Торрес', 'Fernando Torres'),
    ],
    bench: [
      L('GK', 'Ежи Дудек', 'Jerzy Dudek'),
      L('DF', 'Сэми Хююпия', 'Sami Hyypiä'),
      L('DF', 'Дэниел Аггер', 'Daniel Agger'),
      L('MF', 'Фабиньо', 'Fabinho'),
      L('MF', 'Джордан Хендерсон', 'Jordan Henderson'),
      L('FW', 'Робби Фаулер', 'Robbie Fowler'),
      L('FW', 'Дирк Кёйт', 'Dirk Kuyt'),
    ],
  },
  'Lokomotiv Moscow': {
    start: [
      L('GK', 'Маринато Гильерме', 'Marinato Guilherme'),
      L('LB', 'Дмитрий Баринов', 'Dmitry Barinov'),
      L('CB', 'Ведран Чорлука', 'Vedran Ćorluka'),
      L('CB', 'Соломон Кверквелия', 'Solomon Kvirkvelia'),
      L('RB', 'Владислав Игнатьев', 'Vladislav Ignatyev'),
      L('LM', 'Алексей Миранчук', 'Aleksei Miranchuk'),
      L('CM', 'Гжегож Крыховяк', 'Grzegorz Krychowiak'),
      L('CM', 'Игорь Денисов', 'Igor Denisov'),
      L('RM', 'Мануэл Фернандеш', 'Manuel Fernandes'),
      L('ST', 'Фёдор Смолов', 'Fyodor Smolov'),
      L('ST', 'Джефферсон Фарфан', 'Jefferson Farfán'),
    ],
    bench: [
      L('GK', 'Антон Коченков', 'Anton Kochenkov'),
      L('DF', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('DF', 'Неманья Пейчинович', 'Nemanja Pejčinović'),
      L('MF', 'Дмитрий Лоськов', 'Dmitri Loskov'),
      L('MF', 'Рифат Жемалетдинов', 'Rifat Zhemaletdinov'),
      L('FW', 'Алан Касаев', 'Alan Kasaev'),
      L('FW', 'Максим Мухин', 'Maksim Mukhin'),
    ],
  },
}
