import { lineupLine as L } from './bestLineupHelpers'
import type { NationalLineupData } from './nationalBestLineups.types'

export const NATIONAL_LINEUPS_PART2: Record<string, NationalLineupData> = {
  Нидерланды: {
    countryRu: 'Нидерланды',
    start: [
      L('GK', 'Эдвин ван дер Сар', 'Edwin van der Sar'),
      L('LB', 'Джованни ван Бронкхорст', 'Giovanni van Bronckhorst'),
      L('CB', 'Яп Стам', 'Jaap Stam'),
      L('CB', 'Вирджил ван Дейк', 'Virgil van Dijk'),
      L('RB', 'Михаэл Рейзигер', 'Michael Reiziger'),
      L('LM', 'Арьен Роббен', 'Arjen Robben'),
      L('CM', 'Уэсли Снейдер', 'Wesley Sneijder'),
      L('CM', 'Кларенс Зеедорф', 'Clarence Seedorf'),
      L('RM', 'Марк ван Боммел', 'Mark van Bommel'),
      L('ST', 'Руд ван Нистелрой', 'Ruud van Nistelrooy'),
      L('ST', 'Робин ван Перси', 'Robin van Persie'),
    ],
    bench: [
      L('GK', 'Мартен Стекеленбург', 'Maarten Stekelenburg'),
      L('DF', 'Дейли Блинд', 'Daley Blind'),
      L('DF', 'Маттейс де Лигт', 'Matthijs de Ligt'),
      L('MF', 'Френки де Йонг', 'Frenkie de Jong'),
      L('MF', 'Рафаэл ван дер Варт', 'Rafael van der Vaart'),
      L('FW', 'Клас-Ян Хюнтелар', 'Klaas-Jan Huntelaar'),
      L('FW', 'Мемфис Депай', 'Memphis Depay'),
    ],
  },
  Германия: {
    countryRu: 'Германия',
    start: [
      L('GK', 'Мануэль Нойер', 'Manuel Neuer'),
      L('LB', 'Филипп Лам', 'Philipp Lahm'),
      L('CB', 'Матс Хуммельс', 'Mats Hummels'),
      L('CB', 'Жером Боатенг', 'Jérôme Boateng'),
      L('RB', 'Арне Фридрих', 'Arne Friedrich'),
      L('LM', 'Бастиан Швайнштайгер', 'Bastian Schweinsteiger'),
      L('CM', 'Михаэль Баллак', 'Michael Ballack'),
      L('CM', 'Тони Кроос', 'Toni Kroos'),
      L('RM', 'Томас Мюллер', 'Thomas Müller'),
      L('ST', 'Мирослав Клозе', 'Miroslav Klose'),
      L('ST', 'Оливер Бирхофф', 'Oliver Bierhoff'),
    ],
    bench: [
      L('GK', 'Йенс Леманн', 'Jens Lehmann'),
      L('DF', 'Пер Мертезакер', 'Per Mertesacker'),
      L('DF', 'Марсель Хальстенберг', 'Marcel Halstenberg'),
      L('MF', 'Сами Хедира', 'Sami Khedira'),
      L('MF', 'Месут Озиль', 'Mesut Özil'),
      L('FW', 'Марио Гомес', 'Mario Gomez'),
      L('FW', 'Лукас Подольски', 'Lukas Podolski'),
    ],
  },
  Италия: {
    countryRu: 'Италия',
    start: [
      L('GK', 'Джанлуиджи Буффон', 'Gianluigi Buffon'),
      L('LB', 'Паоло Мальдини', 'Paolo Maldini'),
      L('CB', 'Фабио Каннаваро', 'Fabio Cannavaro'),
      L('CB', 'Алессандро Неста', 'Alessandro Nesta'),
      L('RB', 'Джанлука Дзамбротта', 'Gianluca Zambrotta'),
      L('LM', 'Андреа Пирло', 'Andrea Pirlo'),
      L('CM', 'Дженнаро Гаттузо', 'Gennaro Gattuso'),
      L('CM', 'Даниэле Де Росси', 'Daniele De Rossi'),
      L('RM', 'Франческо Тотти', 'Francesco Totti'),
      L('ST', 'Алессандро Дель Пьеро', 'Alessandro Del Piero'),
      L('ST', 'Кристиан Вьери', 'Christian Vieri'),
    ],
    bench: [
      L('GK', 'Марко Сторари', 'Marco Storari'),
      L('DF', 'Леонардо Бонуччи', 'Leonardo Bonucci'),
      L('DF', 'Джорджо Кьеллини', 'Giorgio Chiellini'),
      L('MF', 'Клаудио Маркизио', 'Claudio Marchisio'),
      L('MF', 'Симоне Перротта', 'Simone Perrotta'),
      L('FW', 'Филиппо Индзаги', 'Filippo Inzaghi'),
      L('FW', 'Винченцо Яквинта', 'Vincenzo Iaquinta'),
    ],
  },
  Бельгия: {
    countryRu: 'Бельгия',
    start: [
      L('GK', 'Тибо Куртуа', 'Thibaut Courtois'),
      L('LB', 'Ян Вертонген', 'Jan Vertonghen'),
      L('CB', 'Венсан Компани', 'Vincent Kompany'),
      L('CB', 'Тоби Алдервейрелд', 'Toby Alderweireld'),
      L('RB', 'Томас Мёнье', 'Thomas Meunier'),
      L('LM', 'Эден Азар', 'Eden Hazard'),
      L('CM', 'Кевин Де Брюйне', 'Kevin De Bruyne'),
      L('CM', 'Аксель Витсель', 'Axel Witsel'),
      L('RM', 'Дрис Мертенс', 'Dries Mertens'),
      L('ST', 'Ромелу Лукаку', 'Romelu Lukaku'),
      L('ST', 'Миши Батшуайи', 'Michy Batshuayi'),
    ],
    bench: [
      L('GK', 'Симон Миньоле', 'Simon Mignolet'),
      L('DF', 'Дедрик Бойата', 'Dedryck Boyata'),
      L('DF', 'Данни Ван Бюйтен', 'Danny Van Buyten'),
      L('MF', 'Мусса Дембеле', 'Mousa Dembélé'),
      L('MF', 'Юри Тилеманс', 'Youri Tielemans'),
      L('FW', 'Кристиан Бентеке', 'Christian Benteke'),
      L('FW', 'Дивок Ориги', 'Divock Origi'),
    ],
  },
  Хорватия: {
    countryRu: 'Хорватия',
    start: [
      L('GK', 'Доминик Ливакович', 'Dominik Livaković'),
      L('LB', 'Иван Стринич', 'Ivan Strinić'),
      L('CB', 'Деян Ловрен', 'Dejan Lovren'),
      L('CB', 'Йосип Шимунич', 'Josip Šimunić'),
      L('RB', 'Шиме Врсалько', 'Šime Vrsaljko'),
      L('LM', 'Иван Перишич', 'Ivan Perišić'),
      L('CM', 'Лука Модрич', 'Luka Modrić'),
      L('CM', 'Иван Ракитич', 'Ivan Rakitić'),
      L('RM', 'Марцело Брозович', 'Marcelo Brozović'),
      L('ST', 'Марио Манджукич', 'Mario Mandžukić'),
      L('ST', 'Давор Шукер', 'Davor Šuker'),
    ],
    bench: [
      L('GK', 'Стипе Плетикоса', 'Stipe Pletikosa'),
      L('DF', 'Роберт Ковач', 'Robert Kovač'),
      L('DF', 'Домагой Вида', 'Domagoj Vida'),
      L('MF', 'Никола Кранчар', 'Niko Kranjčar'),
      L('MF', 'Матео Ковачич', 'Mateo Kovačić'),
      L('FW', 'Ивица Олич', 'Ivica Olić'),
      L('FW', 'Анте Ребич', 'Ante Rebić'),
    ],
  },
  Уругвай: {
    countryRu: 'Уругвай',
    start: [
      L('GK', 'Фернандо Муслера', 'Fernando Muslera'),
      L('LB', 'Мартин Касерес', 'Martín Cáceres'),
      L('CB', 'Диего Годин', 'Diego Godín'),
      L('CB', 'Хосе Мария Хименес', 'José María Giménez'),
      L('RB', 'Макси Перейра', 'Maxi Pereira'),
      L('LM', 'Кристиан Родригес', 'Cristian Rodríguez'),
      L('CM', 'Федерико Вальверде', 'Federico Valverde'),
      L('CM', 'Родриго Бентанкур', 'Rodrigo Bentancur'),
      L('RM', 'Луис Суарес', 'Luis Suárez'),
      L('ST', 'Эдинсон Кавани', 'Edinson Cavani'),
      L('ST', 'Диего Форлан', 'Diego Forlán'),
    ],
    bench: [
      L('GK', 'Мартин Сильва', 'Martín Silva'),
      L('DF', 'Себастьян Коатес', 'Sebastián Coates'),
      L('DF', 'Диего Лугано', 'Diego Lugano'),
      L('MF', 'Альваро Перейра', 'Álvaro Pereira'),
      L('MF', 'Николас Лодейро', 'Nicolás Lodeiro'),
      L('FW', 'Кристиан Стуани', 'Cristhian Stuani'),
      L('FW', 'Абель Эрнандес', 'Abel Hernández'),
    ],
  },
}
