import { lineupLine as L } from './bestLineupHelpers'
import type { NationalLineupData } from './nationalBestLineups.types'

export const NATIONAL_LINEUPS_PART3: Record<string, NationalLineupData> = {
  Колумбия: {
    countryRu: 'Колумбия',
    start: [
      L('GK', 'Давид Оспина', 'David Ospina'),
      L('LB', 'Йохан Мохика', 'Johan Mojica'),
      L('CB', 'Иван Кордоба', 'Iván Córdoba'),
      L('CB', 'Марио Йепес', 'Mario Yepes'),
      L('RB', 'Сантьяго Ариас', 'Santiago Arias'),
      L('LM', 'Хуан Куадрадо', 'Juan Cuadrado'),
      L('CM', 'Хамес Родригес', 'James Rodríguez'),
      L('CM', 'Карлос Санчес', 'Carlos Sánchez'),
      L('RM', 'Фредди Гуарин', 'Freddy Guarín'),
      L('ST', 'Радамель Фалькао', 'Radamel Falcao'),
      L('ST', 'Джексон Мартинес', 'Jackson Martínez'),
    ],
    bench: [
      L('GK', 'Камило Варгас', 'Camilo Vargas'),
      L('DF', 'Йерри Мина', 'Yerry Mina'),
      L('DF', 'Кристиан Сапата', 'Cristián Zapata'),
      L('MF', 'Хуан Кинтеро', 'Juan Quintero'),
      L('MF', 'Эдвин Кардона', 'Edwin Cardona'),
      L('FW', 'Луис Мурьель', 'Luis Muriel'),
      L('FW', 'Теофило Гутьеррес', 'Teófilo Gutiérrez'),
    ],
  },
  Мексика: {
    countryRu: 'Мексика',
    start: [
      L('GK', 'Гильермо Очоа', 'Guillermo Ochoa'),
      L('LB', 'Рафаэль Маркес', 'Rafael Márquez'),
      L('CB', 'Карлос Сальсидо', 'Carlos Salcido'),
      L('CB', 'Эктор Морено', 'Héctor Moreno'),
      L('RB', 'Рикардо Осорио', 'Ricardo Osorio'),
      L('LM', 'Андрес Гуардадо', 'Andrés Guardado'),
      L('CM', 'Хонатан дос Сантос', 'Jonathan dos Santos'),
      L('CM', 'Эктор Эррера', 'Héctor Herrera'),
      L('RM', 'Хесус Корона', 'Jesús Corona'),
      L('ST', 'Харед Боргетти', 'Jared Borgetti'),
      L('ST', 'Карлос Вела', 'Carlos Vela'),
    ],
    bench: [
      L('GK', 'Хосе де Хесус Корона', 'José de Jesús Corona'),
      L('DF', 'Уго Айяла', 'Hugo Ayala'),
      L('DF', 'Павел Пардо', 'Pável Pardo'),
      L('MF', 'Луис Монтес', 'Luis Montes'),
      L('MF', 'Марко Фабиан', 'Marco Fabián'),
      L('FW', 'Хавьер Эрнандес', 'Javier Hernández'),
      L('FW', 'Куаутемок Бланко', 'Cuauhtémoc Blanco'),
    ],
  },
  США: {
    countryRu: 'США',
    start: [
      L('GK', 'Тим Ховард', 'Tim Howard'),
      L('LB', 'Антони Робинсон', 'Antonee Robinson'),
      L('CB', 'Огучи Оньеву', 'Oguchi Onyewu'),
      L('CB', 'Карлос Боканегра', 'Carlos Bocanegra'),
      L('RB', 'Сержиньо Дест', 'Sergiño Dest'),
      L('LM', 'Кристиан Пулишич', 'Christian Pulisic'),
      L('CM', 'Майкл Брэдли', 'Michael Bradley'),
      L('CM', 'Клинт Демпси', 'Clint Dempsey'),
      L('RM', 'Лэндон Донован', 'Landon Donovan'),
      L('ST', 'Брайан Макбрайд', 'Brian McBride'),
      L('ST', 'Джози Алтидор', 'Jozy Altidore'),
    ],
    bench: [
      L('GK', 'Брэд Фридель', 'Brad Friedel'),
      L('DF', 'Стив Черундоло', 'Steve Cherundolo'),
      L('DF', 'Джон Брукс', 'John Brooks'),
      L('MF', 'Таб Рамос', 'Tab Ramos'),
      L('MF', 'Коби Джонс', 'Cobi Jones'),
      L('FW', 'Эрик Виналда', 'Eric Wynalda'),
      L('FW', 'Крис Вондоловски', 'Chris Wondolowski'),
    ],
  },
  Швейцария: {
    countryRu: 'Швейцария',
    start: [
      L('GK', 'Ян Зоммер', 'Yann Sommer'),
      L('LB', 'Рикардо Родригес', 'Ricardo Rodríguez'),
      L('CB', 'Фабиан Шер', 'Fabian Schär'),
      L('CB', 'Мануэль Аканджи', 'Manuel Akanji'),
      L('RB', 'Стефан Лихтштайнер', 'Stephan Lichtsteiner'),
      L('LM', 'Джердан Шакири', 'Xherdan Shaqiri'),
      L('CM', 'Гранит Джака', 'Granit Xhaka'),
      L('CM', 'Денис Закариа', 'Denis Zakaria'),
      L('RM', 'Блерим Джемайли', 'Blerim Džemaili'),
      L('ST', 'Александр Фрай', 'Alexander Frei'),
      L('ST', 'Харрис Сеферович', 'Haris Seferović'),
    ],
    bench: [
      L('GK', 'Диего Бенальо', 'Diego Benaglio'),
      L('DF', 'Франсуа Мбанге', 'François Mbandje'),
      L('DF', 'Лоран Грихтинг', 'Loran Grichting'),
      L('MF', 'Валон Бехрами', 'Valon Behrami'),
      L('MF', 'Ремо Фройлер', 'Remo Freuler'),
      L('FW', 'Эрен Дердийок', 'Eren Derdiyok'),
      L('FW', 'Адмир Мехмеди', 'Admir Mehmedi'),
    ],
  },
  Дания: {
    countryRu: 'Дания',
    start: [
      L('GK', 'Каспер Шмейхель', 'Kasper Schmeichel'),
      L('LB', 'Йенс Стрюгер Ларсен', 'Jens Stryger Larsen'),
      L('CB', 'Симон Кьер', 'Simon Kjær'),
      L('CB', 'Андреас Кристенсен', 'Andreas Christensen'),
      L('RB', 'Даниэль Васс', 'Daniel Wass'),
      L('LM', 'Кристиан Эриксен', 'Christian Eriksen'),
      L('CM', 'Томас Гравесен', 'Thomas Gravesen'),
      L('CM', 'Пьер-Эмиль Хёйбьерг', 'Pierre-Emile Højbjerg'),
      L('RM', 'Мартин Йоргенсен', 'Martin Jørgensen'),
      L('ST', 'Йон Даль Томассон', 'Jon Dahl Tomasson'),
      L('ST', 'Никлас Бентнер', 'Nicklas Bendtner'),
    ],
    bench: [
      L('GK', 'Томас Сёренсен', 'Thomas Sørensen'),
      L('DF', 'Йеспер Бьелланн', 'Jesper Bjelan'),
      L('DF', 'Микаэль Крёльдруп', 'Michael Krohn-Dehli'),
      L('MF', 'Кристиан Поульсен', 'Christian Poulsen'),
      L('MF', 'Деннис Роммедаль', 'Dennis Rommedahl'),
      L('FW', 'Миккель Бекманн', 'Mikkel Beckmann'),
      L('FW', 'Мартин Брейтуэйт', 'Martin Braithwaite'),
    ],
  },
  Швеция: {
    countryRu: 'Швеция',
    start: [
      L('GK', 'Андреас Исакссон', 'Andreas Isaksson'),
      L('LB', 'Микаэль Нильссон', 'Mikael Nilsson'),
      L('CB', 'Олоф Мельберг', 'Olof Mellberg'),
      L('CB', 'Андреас Гранквист', 'Andreas Granqvist'),
      L('RB', 'Микаэль Лустиг', 'Mikael Lustig'),
      L('LM', 'Фредрик Юнгберг', 'Fredrik Ljungberg'),
      L('CM', 'Ким Чельстрем', 'Kim Källström'),
      L('CM', 'Себастьян Ларссон', 'Sebastian Larsson'),
      L('RM', 'Эмиль Халльфредссон', 'Emil Hallfreðsson'),
      L('ST', 'Златан Ибрагимович', 'Zlatan Ibrahimović'),
      L('ST', 'Хенрик Ларссон', 'Henrik Larsson'),
    ],
    bench: [
      L('GK', 'Робин Ульсен', 'Robin Olsen'),
      L('DF', 'Эрик Эдман', 'Erik Edman'),
      L('DF', 'Понтус Янссон', 'Pontus Jansson'),
      L('MF', 'Тобиас Линдерот', 'Tobias Linderoth'),
      L('MF', 'Александер Исак', 'Alexander Isak'),
      L('FW', 'Маркус Берг', 'Marcus Berg'),
      L('FW', 'Юхан Эльмандер', 'Johan Elmander'),
    ],
  },
}
