import { lineupLine as L } from './bestLineupHelpers'
import type { NationalLineupData } from './nationalBestLineups.types'

export const NATIONAL_LINEUPS_PART5: Record<string, NationalLineupData> = {
  Иран: {
    countryRu: 'Иран',
    start: [
      L('GK', 'Алиреза Бейранванд', 'Alireza Beiranvand'),
      L('LB', 'Милад Мохаммади', 'Milad Mohammadi'),
      L('CB', 'Хоссейн Кааби', 'Hossein Kaabi'),
      L('CB', 'Мохаммадреза Ханзаде', 'Mohammadreza Khanzadeh'),
      L('RB', 'Рамин Резеян', 'Ramin Rezaeian'),
      L('LM', 'Мехди Махдавикия', 'Mehdi Mahdavikia'),
      L('CM', 'Джавад Некунам', 'Javad Nekounam'),
      L('CM', 'Али Даеи', 'Ali Daei'),
      L('RM', 'Вахид Хашемян', 'Vahid Hashemian'),
      L('ST', 'Сердар Азмун', 'Sardar Azmoun'),
      L('ST', 'Мехди Тареми', 'Mehdi Taremi'),
    ],
    bench: [
      L('GK', 'Хоссейн Хоссейни', 'Hossein Hosseini'),
      L('DF', 'Мортеза Пурлиганджи', 'Morteza Pouraliganji'),
      L('DF', 'Эхсан Хаджсафи', 'Ehsan Hajsafi'),
      L('MF', 'Али Карими', 'Ali Karimi'),
      L('MF', 'Масуд Шоджаи', 'Masoud Shojaei'),
      L('FW', 'Карим Ансарифард', 'Karim Ansarifard'),
      L('FW', 'Реза Гучаннежад', 'Reza Ghoochannejhad'),
    ],
  },
  Австралия: {
    countryRu: 'Австралия',
    start: [
      L('GK', 'Марк Шварцер', 'Mark Schwarzer'),
      L('LB', 'Крейг Мур', 'Craig Moore'),
      L('CB', 'Лукас Нил', 'Lucas Neill'),
      L('CB', 'Мэттью Шпиранович', 'Matthew Špiranović'),
      L('RB', 'Бретт Эмертон', 'Brett Emerton'),
      L('LM', 'Гарри Кьюэлл', 'Harry Kewell'),
      L('CM', 'Тим Кэхилл', 'Tim Cahill'),
      L('CM', 'Марк Видука', 'Mark Viduka'),
      L('RM', 'Миле Стерьовски', 'Mile Sterjovski'),
      L('ST', 'Джон Алоизи', 'John Aloisi'),
      L('ST', 'Джошуа Кеннеди', 'Joshua Kennedy'),
    ],
    bench: [
      L('GK', 'Адам Федеричи', 'Adam Federici'),
      L('DF', 'Нил Киккен', 'Neil Kicken'),
      L('DF', 'Рис Уильямс', 'Rhys Williams'),
      L('MF', 'Карл Валери', 'Carl Valeri'),
      L('MF', 'Джеймс Троизи', 'James Troisi'),
      L('FW', 'Бретт Холман', 'Brett Holman'),
      L('FW', 'Томми ОАР', 'Tommy Oar'),
    ],
  },
  Чили: {
    countryRu: 'Чили',
    start: [
      L('GK', 'Клаудио Браво', 'Claudio Bravo'),
      L('LB', 'Хуан Фуэнтес', 'Juan Fuentes'),
      L('CB', 'Гари Медель', 'Gary Medel'),
      L('CB', 'Франсиско Сильва', 'Francisco Silva'),
      L('RB', 'Маурисио Исла', 'Mauricio Isla'),
      L('LM', 'Алексис Санчес', 'Alexis Sánchez'),
      L('CM', 'Артуро Видаль', 'Arturo Vidal'),
      L('CM', 'Марсело Диас', 'Marcelo Díaz'),
      L('RM', 'Хорхе Вальдивия', 'Jorge Valdivia'),
      L('ST', 'Иван Саморано', 'Iván Zamorano'),
      L('ST', 'Марсело Салас', 'Marcelo Salas'),
    ],
    bench: [
      L('GK', 'Джонни Эррера', 'Johnny Herrera'),
      L('DF', 'Гонсало Хара', 'Gonzalo Jara'),
      L('DF', 'Эугенио Мена', 'Eugenio Mena'),
      L('MF', 'Чарлес Арангис', 'Charles Aránguiz'),
      L('MF', 'Матиас Фернандес', 'Matías Fernández'),
      L('FW', 'Эдуардо Варгас', 'Eduardo Vargas'),
      L('FW', 'Фабиан Орельяна', 'Fabián Orellana'),
    ],
  },
  Эквадор: {
    countryRu: 'Эквадор',
    start: [
      L('GK', 'Александр Домингес', 'Alexander Domínguez'),
      L('LB', 'Вальтер Айови', 'Walter Ayoví'),
      L('CB', 'Иван Уртадо', 'Iván Hurtado'),
      L('CB', 'Хорхе Гуагуа', 'Jorge Guagua'),
      L('RB', 'Улисес де ла Крус', 'Ulises de la Cruz'),
      L('LM', 'Кристиан Нобоа', 'Christian Noboa'),
      L('CM', 'Сегундо Кастильо', 'Segundo Castillo'),
      L('CM', 'Эдинсон Мендес', 'Edison Méndez'),
      L('RM', 'Антонио Валенсия', 'Antonio Valencia'),
      L('ST', 'Агустин Дельгадо', 'Agustín Delgado'),
      L('ST', 'Эннер Валенсия', 'Enner Valencia'),
    ],
    bench: [
      L('GK', 'Массимо Домингес', 'Máximo Domínguez'),
      L('DF', 'Фрэнк Арройо', 'Frank Arroyo'),
      L('DF', 'Габриэль Агилар', 'Gabriel Aguilar'),
      L('MF', 'Луис Сарата', 'Luis Zaráte'),
      L('MF', 'Павел Кайседо', 'Pável Caicedo'),
      L('FW', 'Фелипе Кайседо', 'Felipe Caicedo'),
      L('FW', 'Хайме Айови', 'Jaime Ayoví'),
    ],
  },
  Сербия: {
    countryRu: 'Сербия',
    start: [
      L('GK', 'Владимир Стойкович', 'Vladimir Stojković'),
      L('LB', 'Александар Коларов', 'Aleksandar Kolarov'),
      L('CB', 'Неманья Видич', 'Nemanja Vidić'),
      L('CB', 'Бранислав Иванович', 'Branislav Ivanović'),
      L('RB', 'Антонио Рукавина', 'Antonio Rukavina'),
      L('LM', 'Деян Станкович', 'Dejan Stanković'),
      L('CM', 'Душан Тадич', 'Dušan Tadić'),
      L('CM', 'Неманья Матич', 'Nemanja Matić'),
      L('RM', 'Милош Красич', 'Miloš Krasić'),
      L('ST', 'Саво Милошевич', 'Savo Milošević'),
      L('ST', 'Никола Жигич', 'Nikola Žigić'),
    ],
    bench: [
      L('GK', 'Желько Бркич', 'Željko Brkić'),
      L('DF', 'Младен Крстаич', 'Mladen Krstajić'),
      L('DF', 'Невен Суботич', 'Neven Subotić'),
      L('MF', 'Зоран Тошич', 'Zoran Tošić'),
      L('MF', 'Милош Вулетич', 'Miloš Vuletic'),
      L('FW', 'Марко Пантелич', 'Marko Pantelić'),
      L('FW', 'Дарко Ковачевич', 'Darko Kovačević'),
    ],
  },
  Турция: {
    countryRu: 'Турция',
    start: [
      L('GK', 'Рюштю Речбер', 'Rüştü Reçber'),
      L('LB', 'Хакан Балта', 'Hakan Balta'),
      L('CB', 'Булент Коркмаз', 'Bülent Korkmaz'),
      L('CB', 'Алпай Озалан', 'Alpay Özalan'),
      L('RB', 'Сабри Сарыоглу', 'Sabri Sarıoğlu'),
      L('LM', 'Арда Туран', 'Arda Turan'),
      L('CM', 'Эмре Белёзоглу', 'Emre Belözoğlu'),
      L('CM', 'Хакан Чалханоглу', 'Hakan Çalhanoğlu'),
      L('RM', 'Тугай Керимоглу', 'Tugay Kerimoğlu'),
      L('ST', 'Хакан Шукюр', 'Hakan Şükür'),
      L('ST', 'Нихат Кахведжи', 'Nihat Kahveci'),
    ],
    bench: [
      L('GK', 'Волкан Демирель', 'Volkan Demirel'),
      L('DF', 'Гёкхан Зан', 'Gökhan Zan'),
      L('DF', 'Сервет Четин', 'Servet Çetin'),
      L('MF', 'Мехмет Топал', 'Mehmet Topal'),
      L('MF', 'Эрдинч Карагёз', 'Erdinç Karagöz'),
      L('FW', 'Ильхан Мансыз', 'İlhan Mansız'),
      L('FW', 'Бурак Йылмаз', 'Burak Yılmaz'),
    ],
  },
}
